import type{PlayerProfile}from'../types/game';
import{applyProfessionalReputation}from'./professionalActTwo';
import{reconcileLegalPrestige}from'./legalPrestige';
import{supabase}from'./supabase';
export type AcademicPublicationType='ARTICLE'|'LECTURE'|'CONGRESS'|'BOOK';
export type TeachingRank='NONE'|'LECTURER'|'PROFESSOR'|'POSTGRAD_PROFESSOR';
export interface AcademicPublication{id:string;type:AcademicPublicationType;title:string;gameDate:string;impact:number}
export interface AcademicCareerState{masterLevel:number;doctorateLevel:number;teachingRank:TeachingRank;institution:string|null;weeklyHours:number;monthlySalary:number;classesTaught:number;publications:AcademicPublication[];lastTeachingMonth:string|null;processedKeys:string[]}
const PREFIX='rota_academic_career_v2:';
const base=():AcademicCareerState=>({masterLevel:0,doctorateLevel:0,teachingRank:'NONE',institution:null,weeklyHours:0,monthlySalary:0,classesTaught:0,publications:[],lastTeachingMonth:null,processedKeys:[]});
const owner=(p:PlayerProfile)=>p.cloudCareerId||p.oabRegistration?.code||p.name||'player';
const date=(p:PlayerProfile)=>[p.gameCurrentYear,String(p.gameCurrentMonth).padStart(2,'0'),String(p.gameCurrentDay).padStart(2,'0')].join('-');
const month=(p:PlayerProfile)=>[p.gameCurrentYear,String(p.gameCurrentMonth).padStart(2,'0')].join('-');
function legacy(p:PlayerProfile){const x=p as PlayerProfile&{masterLevel?:number;doctorateLevel?:number};return{masterLevel:Number(x.masterLevel||0),doctorateLevel:Number(x.doctorateLevel||0)}}
export function readAcademicCareer(p:PlayerProfile){let s=base();if(typeof window!=='undefined')try{s={...s,...JSON.parse(localStorage.getItem(PREFIX+owner(p))||'{}')} }catch{}const l=legacy(p);s.masterLevel=Math.max(s.masterLevel,l.masterLevel);s.doctorateLevel=Math.max(s.doctorateLevel,l.doctorateLevel);return s}
function cache(p:PlayerProfile,s:AcademicCareerState){if(typeof window!=='undefined')localStorage.setItem(PREFIX+owner(p),JSON.stringify(s))}
async function persist(p:PlayerProfile,s:AcademicCareerState){cache(p,s);if(supabase&&p.cloudCareerId)await supabase.from('careers').update({academic_career:s,master_level:s.masterLevel,doctorate_level:s.doctorateLevel,last_played_at:new Date().toISOString()}).eq('id',p.cloudCareerId)}
export async function hydrateAcademicCareer(p:PlayerProfile){if(supabase&&p.cloudCareerId){const{data}=await supabase.from('careers').select('academic_career,master_level,doctorate_level').eq('id',p.cloudCareerId).maybeSingle();if(data){const remote={...base(),...(data.academic_career||{}),masterLevel:Math.max(Number(data.master_level||0),Number(data.academic_career?.masterLevel||0)),doctorateLevel:Math.max(Number(data.doctorate_level||0),Number(data.academic_career?.doctorateLevel||0))};cache(p,remote);return remote}}return readAcademicCareer(p)}
export function teachingEligibility(p:PlayerProfile){const s=readAcademicCareer(p);if(s.doctorateLevel>=3)return{eligible:true,rank:'POSTGRAD_PROFESSOR' as const,hours:12,salary:7800};if(s.masterLevel>=5||s.doctorateLevel>=1)return{eligible:true,rank:'PROFESSOR' as const,hours:10,salary:5600};if(s.masterLevel>=2)return{eligible:true,rank:'LECTURER' as const,hours:6,salary:3200};return{eligible:false,rank:'NONE' as const,hours:0,salary:0}}
export async function acceptTeachingPosition(p:PlayerProfile,institution='Faculdade de Direito'){const s=readAcademicCareer(p),e=teachingEligibility(p);if(!e.eligible)return{ok:false as const,reason:'ACADEMIC_REQUIREMENT' as const};const next={...s,teachingRank:e.rank,institution,weeklyHours:e.hours,monthlySalary:e.salary};await persist(p,next);applyProfessionalReputation(p,{technical:2,institutionalRespect:3,publicRecognition:1},'Ingresso na docência jurídica','teaching-position:'+e.rank);await reconcileLegalPrestige(p,'Ingresso na docência jurídica');return{ok:true as const,state:next}}
export async function leaveTeachingPosition(p:PlayerProfile){const s=readAcademicCareer(p),next={...s,teachingRank:'NONE' as const,institution:null,weeklyHours:0,monthlySalary:0};await persist(p,next);return next}
export async function teachAcademicMonth(p:PlayerProfile){const s=readAcademicCareer(p),key=month(p);if(s.teachingRank==='NONE')return{ok:false as const,reason:'NOT_TEACHING' as const};if(s.lastTeachingMonth===key)return{ok:false as const,reason:'ALREADY_TAUGHT' as const};const next={...s,classesTaught:s.classesTaught+Math.max(4,s.weeklyHours*4),lastTeachingMonth:key};await persist(p,next);applyProfessionalReputation(p,{technical:1,institutionalRespect:1,clientReputation:1},'Atuação docente no ensino jurídico','teaching:'+key);return{ok:true as const,state:next,salary:s.monthlySalary,timeHours:s.weeklyHours*4}}
const pubCfg:Record<AcademicPublicationType,{minMaster:number;minDoctorate:number;cost:number;impact:number;label:string}>={ARTICLE:{minMaster:1,minDoctorate:0,cost:350,impact:2,label:'Artigo jurídico'},LECTURE:{minMaster:2,minDoctorate:0,cost:200,impact:3,label:'Palestra acadêmica'},CONGRESS:{minMaster:4,minDoctorate:0,cost:900,impact:5,label:'Congresso jurídico'},BOOK:{minMaster:5,minDoctorate:2,cost:4500,impact:10,label:'Livro jurídico'}};
export function academicPublicationOptions(p:PlayerProfile){const s=readAcademicCareer(p);return(Object.keys(pubCfg)as AcademicPublicationType[]).map(type=>({type,...pubCfg[type],eligible:s.masterLevel>=pubCfg[type].minMaster&&s.doctorateLevel>=pubCfg[type].minDoctorate}))}
export async function publishAcademicWork(p:PlayerProfile,type:AcademicPublicationType,title:string){const s=readAcademicCareer(p),cfg=pubCfg[type],key=[type,date(p),title.trim().toLowerCase()].join(':');if(!title.trim())return{ok:false as const,reason:'TITLE_REQUIRED' as const};if(s.processedKeys.includes(key))return{ok:false as const,reason:'DUPLICATE' as const};if(s.masterLevel<cfg.minMaster||s.doctorateLevel<cfg.minDoctorate)return{ok:false as const,reason:'ACADEMIC_REQUIREMENT' as const};if(p.money<cfg.cost)return{ok:false as const,reason:'MONEY' as const};const publication={id:key,type,title:title.trim(),gameDate:date(p),impact:cfg.impact};const next={...s,publications:[publication,...s.publications].slice(0,100),processedKeys:[...s.processedKeys,key].slice(-250)};await persist(p,next);applyProfessionalReputation(p,{technical:cfg.impact,publicRecognition:Math.ceil(cfg.impact*.7),institutionalRespect:Math.ceil(cfg.impact*.6),marketPrestige:Math.ceil(cfg.impact*.4)},cfg.label+' publicado','academic-publication:'+key);await reconcileLegalPrestige(p,cfg.label+' ampliou a autoridade acadêmica');return{ok:true as const,state:next,cost:cfg.cost,publication}}
export async function syncAcademicLevels(p:PlayerProfile,masterLevel:number,doctorateLevel:number){const s=readAcademicCareer(p),next={...s,masterLevel:Math.max(s.masterLevel,masterLevel),doctorateLevel:Math.max(s.doctorateLevel,doctorateLevel)};await persist(p,next);return next}