import type{LegalCase,PlayerProfile}from'../types/game';
import{getCaseRepercussionLevel}from'./caseMetadata';
import{getLegalReputationSnapshot,readProfessionalPortfolio}from'./professionalActTwo';
import{supabase}from'./supabase';
export type LegalPrestigeTier='LOCAL'|'REGIONAL'|'ESTADUAL'|'NACIONAL';
export interface LegalPrestigeState{tier:LegalPrestigeTier;score:number;peakTier:LegalPrestigeTier;promotedAt:string|null;lastReason:string|null;processedKeys:string[]}
export interface LegalPrestigeSnapshot extends LegalPrestigeState{nextTier:LegalPrestigeTier|null;nextThreshold:number;progress:number;requirements:string[]}
const PREFIX='rota_legal_prestige_v1:';
const order:LegalPrestigeTier[]=['LOCAL','REGIONAL','ESTADUAL','NACIONAL'];
export const LEGAL_PRESTIGE_CONFIG:Record<LegalPrestigeTier,{label:string;minScore:number;description:string}>={LOCAL:{label:'Local',minScore:0,description:'Nome reconhecido na cidade e no círculo profissional próximo.'},REGIONAL:{label:'Regional',minScore:30,description:'Reconhecimento alcança cidades e profissionais da região.'},ESTADUAL:{label:'Estadual',minScore:58,description:'Nome conhecido no mercado jurídico do estado.'},NACIONAL:{label:'Nacional',minScore:82,description:'Atuação reconhecida além das fronteiras estaduais.'}};
const owner=(p:PlayerProfile)=>p.cloudCareerId||p.oabRegistration?.code||p.name||'player';
const base=():LegalPrestigeState=>({tier:'LOCAL',score:0,peakTier:'LOCAL',promotedAt:null,lastReason:null,processedKeys:[]});
const gameDate=(p:PlayerProfile)=>[p.gameCurrentYear,String(p.gameCurrentMonth).padStart(2,'0'),String(p.gameCurrentDay).padStart(2,'0')].join('-');
function readLocal(p:PlayerProfile){if(typeof window==='undefined')return base();try{const x=JSON.parse(localStorage.getItem(PREFIX+owner(p))||'{}');return{...base(),...x,processedKeys:Array.isArray(x.processedKeys)?x.processedKeys:[]}as LegalPrestigeState}catch{return base()}}
function writeLocal(p:PlayerProfile,s:LegalPrestigeState){if(typeof window!=='undefined')try{localStorage.setItem(PREFIX+owner(p),JSON.stringify(s))}catch{}}
function derivedScore(p:PlayerProfile){const r=getLegalReputationSnapshot(p),portfolio=readProfessionalPortfolio(p);const specs=portfolio.specializations;const authority=specs.filter(s=>s.level==='AUTHORITY').length,regional=specs.filter(s=>s.level==='REGIONAL_REFERENCE').length;const career=Math.min(18,p.casesSolved*.7);return Math.min(100,Math.round(r.technical*.18+r.publicRecognition*.2+r.marketPrestige*.2+r.institutionalRespect*.17+r.clientReputation*.08+career+authority*7+regional*3))}
function qualifies(p:PlayerProfile,t:LegalPrestigeTier,score:number){const r=getLegalReputationSnapshot(p),portfolio=readProfessionalPortfolio(p),spec=portfolio.specializations;if(t==='LOCAL')return true;if(t==='REGIONAL')return score>=30&&p.casesSolved>=3&&r.technical>=35&&r.marketPrestige>=25;if(t==='ESTADUAL')return score>=58&&p.casesSolved>=8&&r.publicRecognition>=35&&r.institutionalRespect>=40&&spec.some(s=>s.level==='REGIONAL_REFERENCE'||s.level==='AUTHORITY');return score>=82&&p.casesSolved>=15&&r.publicRecognition>=60&&r.institutionalRespect>=60&&r.marketPrestige>=60&&spec.some(s=>s.level==='AUTHORITY')}
function tierFor(p:PlayerProfile,score:number){let t:LegalPrestigeTier='LOCAL';for(const x of order)if(qualifies(p,x,score))t=x;return t}
async function persist(p:PlayerProfile,s:LegalPrestigeState){writeLocal(p,s);if(!supabase||!p.cloudCareerId)return;await supabase.from('careers').update({legal_prestige:s,last_played_at:new Date().toISOString()}).eq('id',p.cloudCareerId)}
export function getLegalPrestigeSnapshot(p:PlayerProfile):LegalPrestigeSnapshot{const stored=readLocal(p),score=Math.max(stored.score,derivedScore(p)),calculated=tierFor(p,score),tier=order.indexOf(calculated)>order.indexOf(stored.tier)?calculated:stored.tier,peakTier=order.indexOf(tier)>order.indexOf(stored.peakTier)?tier:stored.peakTier,nextTier=order[order.indexOf(tier)+1]||null,nextThreshold=nextTier?LEGAL_PRESTIGE_CONFIG[nextTier].minScore:100;const current=LEGAL_PRESTIGE_CONFIG[tier].minScore,progress=tier==='NACIONAL'?100:Math.max(0,Math.min(100,Math.round((score-current)/(nextThreshold-current)*100)));return{...stored,tier,peakTier,score,nextTier,nextThreshold,progress,requirements:nextTier?requirementsFor(p,nextTier,score):['Prestígio nacional consolidado']}}
function requirementsFor(p:PlayerProfile,t:LegalPrestigeTier,score:number){const r=getLegalReputationSnapshot(p),s=readProfessionalPortfolio(p).specializations;if(t==='REGIONAL')return[score>=30?'✓ Índice 30+':'Índice 30+',p.casesSolved>=3?'✓ 3 casos concluídos':'3 casos concluídos',r.technical>=35?'✓ Técnica 35+':'Técnica 35+',r.marketPrestige>=25?'✓ Mercado 25+':'Mercado 25+'];if(t==='ESTADUAL')return[score>=58?'✓ Índice 58+':'Índice 58+',p.casesSolved>=8?'✓ 8 casos concluídos':'8 casos concluídos',r.publicRecognition>=35?'✓ Reconhecimento público 35+':'Reconhecimento público 35+',r.institutionalRespect>=40?'✓ Institucional 40+':'Institucional 40+',s.some(x=>x.level==='REGIONAL_REFERENCE'||x.level==='AUTHORITY')?'✓ Referência regional':'Especialização: referência regional'];return[score>=82?'✓ Índice 82+':'Índice 82+',p.casesSolved>=15?'✓ 15 casos concluídos':'15 casos concluídos',r.publicRecognition>=60?'✓ Reconhecimento público 60+':'Reconhecimento público 60+',r.institutionalRespect>=60?'✓ Institucional 60+':'Institucional 60+',r.marketPrestige>=60?'✓ Mercado 60+':'Mercado 60+',s.some(x=>x.level==='AUTHORITY')?'✓ Autoridade em especialização':'Especialização: autoridade']}
export async function reconcileLegalPrestige(p:PlayerProfile,reason='Evolução profissional'){const old=readLocal(p),snap=getLegalPrestigeSnapshot(p),promoted=order.indexOf(snap.tier)>order.indexOf(old.tier);const next:LegalPrestigeState={tier:snap.tier,score:snap.score,peakTier:snap.peakTier,promotedAt:promoted?gameDate(p):old.promotedAt,lastReason:promoted?reason:old.lastReason,processedKeys:old.processedKeys};if(JSON.stringify(old)!==JSON.stringify(next))await persist(p,next);return{state:next,promoted}}
export async function recordPrestigeCaseOutcome(p:PlayerProfile,c:LegalCase,success:boolean){const old=readLocal(p),key='case:'+c.id;if(old.processedKeys.includes(key))return reconcileLegalPrestige(p);const level=getCaseRepercussionLevel(c),bonus=success?(level==='NACIONAL'?12:level==='GRANDE_REPERCUSSAO'?8:level==='RELEVANTE'?4:1):(level==='NACIONAL'?-3:level==='GRANDE_REPERCUSSAO'?-2:0);const next={...old,score:Math.max(0,Math.min(100,old.score+bonus)),processedKeys:[...old.processedKeys,key].slice(-300),lastReason:success?'Resultado que ampliou o alcance profissional':'Resultado de repercussão desfavorável'};await persist(p,next);return reconcileLegalPrestige(p,next.lastReason||undefined)}
export async function hydrateLegalPrestige(p:PlayerProfile){if(!supabase||!p.cloudCareerId)return reconcileLegalPrestige(p);const{data}=await supabase.from('careers').select('legal_prestige').eq('id',p.cloudCareerId).maybeSingle();if(data?.legal_prestige){const remote={...base(),...data.legal_prestige,processedKeys:Array.isArray(data.legal_prestige.processedKeys)?data.legal_prestige.processedKeys:[]}as LegalPrestigeState;writeLocal(p,remote)}return reconcileLegalPrestige(p)}
export function prestigeAllowsCase(p:PlayerProfile,c:LegalCase){const t=getLegalPrestigeSnapshot(p).tier,l=getCaseRepercussionLevel(c);if(l==='NACIONAL')return t==='NACIONAL'||t==='ESTADUAL';if(l==='GRANDE_REPERCUSSAO')return t!=='LOCAL';return true}
export function prestigeReachMultiplier(p:PlayerProfile){return{LOCAL:1,REGIONAL:1.15,ESTADUAL:1.35,NACIONAL:1.65}[getLegalPrestigeSnapshot(p).tier]}