import type { LegalCase,PlayerProfile } from '../types/game';
import { getCaseRepercussionLevel,type CaseRepercussionLevel } from './caseMetadata';
import { applyProfessionalReputation } from './professionalActTwo';
import { applyWorldMemoryEvent } from './worldMemory';
import { supabase } from './supabase';
export type MediaStrategy='SILENCE'|'TECHNICAL_STATEMENT'|'INTERVIEW'|'SOCIAL_MEDIA';
export interface MediaEvent{id:string;caseId:string;eventKey:string;eventType:string;gameDate:string;repercussionLevel:CaseRepercussionLevel;headline:string;summary:string;exposure:number;sentiment:number;legalRisk:number;clientImpact:number;institutionalImpact:number;responseStrategy:MediaStrategy|null}
const date=(p:PlayerProfile)=>[p.gameCurrentYear,String(p.gameCurrentMonth).padStart(2,'0'),String(p.gameCurrentDay).padStart(2,'0')].join('-');
const scale=(l:CaseRepercussionLevel)=>l==='NACIONAL'?100:l==='GRANDE_REPERCUSSAO'?70:l==='RELEVANTE'?35:0;
export function isMediaCase(c:LegalCase){return getCaseRepercussionLevel(c)!=='COMUM'}
export async function createCaseMediaEvent(p:PlayerProfile,c:LegalCase,eventType:'CASE_OPENED'|'HEARING'|'DECISION',success?:boolean){
 const level=getCaseRepercussionLevel(c);if(level==='COMUM'||!supabase||!p.cloudCareerId)return null;const {data:user}=await supabase.auth.getUser();if(!user.user)return null;const key=[eventType,c.id].join(':');const base=scale(level);const sentiment=success===undefined?0:success?Math.round(base*.25):-Math.round(base*.2);
 const headline=eventType==='CASE_OPENED'?'Caso '+c.title+' ganha repercussão':eventType==='HEARING'?'Audiência de '+c.title+' atrai atenção pública':'Decisão em '+c.title+' repercute no meio jurídico';const summary='O caso '+c.title+' passou a integrar o debate público.';
 const row={career_id:p.cloudCareerId,user_id:user.user.id,case_id:c.id,event_key:key,event_type:eventType,game_date:date(p),repercussion_level:level,headline,summary,exposure:base,sentiment,legal_risk:Math.round(base*.1),client_impact:sentiment,institutional_impact:Math.round(sentiment*.6)};
 const {data}=await supabase.from('career_media_events').upsert(row,{onConflict:'career_id,event_key'}).select('*').single();if(!data)return null;if(success!==undefined)applyProfessionalReputation(p,{publicRecognition:success?Math.max(1,Math.round(base/20)):0,marketPrestige:success?Math.max(1,Math.round(base/30)):-Math.max(1,Math.round(base/40)),institutionalRespect:success?2:-2},'Repercussão de caso público','media:'+key);
 await applyWorldMemoryEvent(p,{memoryKey:'media:'+key,kind:'PUBLIC_CASE',title:headline,description:summary,scope:level==='NACIONAL'?'NATIONAL':level==='GRANDE_REPERCUSSAO'?'REGIONAL':'PROFESSIONAL_COMMUNITY',intensity:base,sourceCaseId:c.id,respectDelta:success===undefined?0:success?4:-2,trustDelta:success===undefined?0:success?2:-2,rivalryDelta:success?2:0});return data;
}
export async function respondToMedia(p:PlayerProfile,event:MediaEvent,strategy:MediaStrategy){
 if(!supabase||!p.cloudCareerId||event.responseStrategy)return{ok:false as const,reason:'USED' as const};const effects={SILENCE:{pub:0,market:0,inst:2,risk:-4},TECHNICAL_STATEMENT:{pub:2,market:1,inst:3,risk:-2},INTERVIEW:{pub:6,market:3,inst:-1,risk:5},SOCIAL_MEDIA:{pub:8,market:2,inst:-3,risk:8}}[strategy];
 const {error}=await supabase.from('career_media_events').update({response_strategy:strategy,exposure:event.exposure+effects.pub*2,legal_risk:Math.max(0,event.legalRisk+effects.risk),institutional_impact:event.institutionalImpact+effects.inst}).eq('id',event.id).eq('career_id',p.cloudCareerId);if(error)return{ok:false as const,reason:'DB' as const};
 applyProfessionalReputation(p,{publicRecognition:effects.pub,marketPrestige:effects.market,institutionalRespect:effects.inst},'Estratégia de comunicação em caso de repercussão','media-response:'+event.id);
 await applyWorldMemoryEvent(p,{memoryKey:'media-response:'+event.id,kind:'MEDIA_RESPONSE',title:'Posicionamento público do advogado',description:'Estratégia adotada: '+strategy+'.',scope:event.repercussionLevel==='NACIONAL'?'NATIONAL':'PROFESSIONAL_COMMUNITY',intensity:Math.min(100,event.exposure),sourceCaseId:event.caseId,respectDelta:effects.inst,trustDelta:strategy==='TECHNICAL_STATEMENT'?3:0,rivalryDelta:strategy==='SOCIAL_MEDIA'?3:0});return{ok:true as const};
}
export async function loadMediaEvents(p:PlayerProfile):Promise<MediaEvent[]>{if(!supabase||!p.cloudCareerId)return[];const {data}=await supabase.from('career_media_events').select('*').eq('career_id',p.cloudCareerId).order('game_date',{ascending:false});return(data||[]).map((x:any)=>({id:x.id,caseId:x.case_id,eventKey:x.event_key,eventType:x.event_type,gameDate:x.game_date,repercussionLevel:x.repercussion_level,headline:x.headline,summary:x.summary,exposure:x.exposure,sentiment:x.sentiment,legalRisk:x.legal_risk,clientImpact:x.client_impact,institutionalImpact:x.institutional_impact,responseStrategy:x.response_strategy}))}