import type { PlayerProfile } from '../types/game';
import { supabase } from './supabase';
import { getProfessionalOwnerKey } from './professionalRpg';

export type OfficeOccupancyType='NONE'|'RENT'|'OWNED';
export type OfficeStaffRole='INTERN'|'ASSISTANT'|'JUNIOR_LAWYER'|'MID_LAWYER'|'SENIOR_LAWYER';
export interface CommercialProperty {id:string;establishmentId:string;realtorName:string;title:string;address:string;areaM2:number;roomCount:number;capacity:number;listingType:'RENT'|'SALE'|'BOTH';rentMonthly:number|null;salePrice:number|null;condominiumMonthly:number;propertyTaxMonthly:number;depositMonths:number;infrastructureLevel:number}
export interface OfficeStaff {id:string;name:string;roleType:OfficeStaffRole;salaryMonthly:number;technicalSkill:number;clientSkill:number;productivity:number;loyalty:number;status:'ACTIVE'|'TERMINATED';hiredGameDate:string;experience:number;workload:number;morale:number;specialization:string|null;semester:number|null;oabStatus:'NOT_APPLICABLE'|'STUDYING'|'ELIGIBLE'|'APPROVED'}
export interface OfficeBusinessState {version:1;id:string|null;lawFirmId:string|null;officeName:string;status:'PLANNING'|'ACTIVE'|'SUSPENDED'|'CLOSED';occupancyType:OfficeOccupancyType;property:CommercialProperty|null;bankBalance:number;infrastructureLevel:number;staff:OfficeStaff[];lastSettlementGameMonth:string|null;openedGameDate:string|null}
const PREFIX='rota_office_business_v1:';
const empty=():OfficeBusinessState=>({version:1,id:null,lawFirmId:null,officeName:'',status:'PLANNING',occupancyType:'NONE',property:null,bankBalance:0,infrastructureLevel:1,staff:[],lastSettlementGameMonth:null,openedGameDate:null});
const key=(p:PlayerProfile)=>PREFIX+getProfessionalOwnerKey(p);
const date=(p:PlayerProfile)=>`${p.gameCurrentYear}-${String(p.gameCurrentMonth).padStart(2,'0')}-${String(p.gameCurrentDay).padStart(2,'0')}`;
export function readOfficeBusiness(p:PlayerProfile){if(typeof window==='undefined')return empty();try{const raw=localStorage.getItem(key(p));return raw?{...empty(),...JSON.parse(raw)}:empty()}catch{return empty()}}
function cache(p:PlayerProfile,s:OfficeBusinessState){if(typeof window!=='undefined')try{localStorage.setItem(key(p),JSON.stringify(s));window.dispatchEvent(new CustomEvent('rota:office-business-updated'))}catch{/*cache*/}}
export async function loadCommercialProperties(p:PlayerProfile):Promise<CommercialProperty[]>{
 if(!supabase)return[];const {data,error}=await supabase.from('commercial_properties').select('*,establishments!inner(name,business_type)').eq('status','published').eq('is_active',true);
 if(error){console.warn('[Ato 3] Imóveis comerciais indisponíveis.',error.message);return[]}
 return (data||[]).filter((r:any)=>String(r.establishments?.business_type||'').toUpperCase()==='IMOBILIARIA').map((r:any)=>({id:r.id,establishmentId:r.establishment_id,realtorName:r.establishments.name,title:r.title,address:r.address_text,areaM2:Number(r.area_m2),roomCount:r.room_count,capacity:r.capacity,listingType:r.listing_type,rentMonthly:r.rent_monthly_jr==null?null:Number(r.rent_monthly_jr),salePrice:r.sale_price_jr==null?null:Number(r.sale_price_jr),condominiumMonthly:Number(r.condominium_monthly_jr||0),propertyTaxMonthly:Number(r.property_tax_monthly_jr||0),depositMonths:r.deposit_months,infrastructureLevel:r.infrastructure_level}));
}
export async function hydrateOfficeBusiness(p:PlayerProfile){
 if(!supabase||!p.cloudCareerId)return readOfficeBusiness(p);
 const {data}=await supabase.from('player_office_businesses').select('*,commercial_properties(*)').eq('career_id',p.cloudCareerId).maybeSingle();if(!data)return readOfficeBusiness(p);
 const {data:staff}=await supabase.from('player_office_staff').select('*').eq('office_business_id',data.id).eq('status','ACTIVE');
 const prop:any=data.commercial_properties;const property=prop?{id:prop.id,establishmentId:prop.establishment_id,realtorName:'Imobiliária',title:prop.title,address:prop.address_text,areaM2:Number(prop.area_m2),roomCount:prop.room_count,capacity:prop.capacity,listingType:prop.listing_type,rentMonthly:prop.rent_monthly_jr==null?null:Number(prop.rent_monthly_jr),salePrice:prop.sale_price_jr==null?null:Number(prop.sale_price_jr),condominiumMonthly:Number(prop.condominium_monthly_jr||0),propertyTaxMonthly:Number(prop.property_tax_monthly_jr||0),depositMonths:prop.deposit_months,infrastructureLevel:prop.infrastructure_level}:null;
 const state:OfficeBusinessState={version:1,id:data.id,lawFirmId:data.law_firm_id,officeName:data.office_name,status:data.business_status,occupancyType:data.occupancy_type,property,bankBalance:Number(data.bank_balance||0),infrastructureLevel:data.infrastructure_level,staff:(staff||[]).map((x:any)=>({id:x.id,name:x.name,roleType:x.role_type,salaryMonthly:Number(x.salary_monthly_jr),technicalSkill:x.technical_skill,clientSkill:x.client_skill,productivity:x.productivity,loyalty:x.loyalty,status:x.status,hiredGameDate:x.hired_game_date,experience:x.experience||0,workload:x.workload||0,morale:x.morale??70,specialization:x.specialization||null,semester:x.semester||null,oabStatus:x.oab_status||'NOT_APPLICABLE'})),lastSettlementGameMonth:data.last_settlement_game_month,openedGameDate:data.opened_game_date};cache(p,state);return state;
}
export function officeMonthlyCost(s:OfficeBusinessState){const salaries=s.staff.filter(x=>x.status==='ACTIVE').reduce((n,x)=>n+x.salaryMonthly,0);const property=s.property?(s.occupancyType==='RENT'?(s.property.rentMonthly||0):s.property.propertyTaxMonthly)+s.property.condominiumMonthly:0;return salaries+property+350+s.staff.length*90}
export async function acquireCommercialProperty(p:PlayerProfile,property:CommercialProperty,mode:'RENT'|'OWNED',officeName:string){
 if(!supabase||!p.cloudCareerId)return{ok:false as const,reason:'CLOUD' as const};const current=readOfficeBusiness(p);if(current.status==='ACTIVE')return{ok:false as const,reason:'ACTIVE' as const};
 const upfront=mode==='RENT'?(property.rentMonthly||0)*Math.max(1,property.depositMonths):(property.salePrice||0);if(p.money<upfront)return{ok:false as const,reason:'MONEY' as const};
 const {data:firm,error:firmError}=await supabase.from('law_firms').insert({slug:`player-${p.cloudCareerId}`,name:officeName,legal_name:officeName,status:'published',is_active:true,market_tier:'LOCAL',size_category:'SMALL',prestige:5,public_reputation:5,ownership_type:'PLAYER',owner_career_id:p.cloudCareerId,location:{city:p.homeCity,state:p.homeState}}).select('id').single();if(firmError)return{ok:false as const,reason:'FIRM' as const};
 const {data:business,error}=await supabase.from('player_office_businesses').insert({career_id:p.cloudCareerId,law_firm_id:firm.id,commercial_property_id:property.id,office_name:officeName,occupancy_type:mode,business_status:'ACTIVE',bank_balance:0,infrastructure_level:property.infrastructureLevel,opened_game_date:date(p)}).select('id').single();if(error)return{ok:false as const,reason:'BUSINESS' as const};
 await supabase.from('careers').update({money:p.money-upfront,career_stage:'DONO_ESCRITORIO'}).eq('id',p.cloudCareerId);
 const next:OfficeBusinessState={...current,id:business.id,lawFirmId:firm.id,officeName,status:'ACTIVE',occupancyType:mode,property,openedGameDate:date(p)};cache(p,next);return{ok:true as const,state:next,upfront};
}
export function generateOfficeCandidates(p:PlayerProfile,s:OfficeBusinessState){
 const seed=(p.gameCurrentYear*372+p.gameCurrentMonth*31+p.gameCurrentDay+s.staff.length*17)>>>0;const names=['Ana Martins','Lucas Ribeiro','Mariana Lopes','Felipe Costa','Camila Nunes','Rafael Moreira'];const roles:OfficeStaffRole[]=['INTERN','ASSISTANT','JUNIOR_LAWYER','MID_LAWYER','SENIOR_LAWYER'];
 return [0,1,2].map(i=>{const n=(seed+i*97)%100;const role=roles[(seed+i)%roles.length];const base={INTERN:1200,ASSISTANT:2400,JUNIOR_LAWYER:3800,MID_LAWYER:5600,SENIOR_LAWYER:8200}[role];return{id:`candidate:${date(p)}:${i}`,name:names[(seed+i*3)%names.length],roleType:role,salaryMonthly:base+(n%5)*150,technicalSkill:30+(n%55),clientSkill:25+((n*3)%60),productivity:30+((n*7)%55),loyalty:40+((n*5)%45)}});
}
export async function hireOfficeCandidate(p:PlayerProfile,c:ReturnType<typeof generateOfficeCandidates>[number]){
 const s=readOfficeBusiness(p);if(!supabase||!s.id)return{ok:false as const,reason:'CLOUD' as const};if(!s.property||s.staff.filter(x=>x.status==='ACTIVE').length+1>=s.property.capacity)return{ok:false as const,reason:'CAPACITY' as const};
 const {data,error}=await supabase.from('player_office_staff').insert({office_business_id:s.id,name:c.name,role_type:c.roleType,salary_monthly_jr:c.salaryMonthly,technical_skill:c.technicalSkill,client_skill:c.clientSkill,productivity:c.productivity,loyalty:c.loyalty,hired_game_date:date(p),semester:c.roleType==='INTERN'?7:null,oab_status:c.roleType==='INTERN'?'STUDYING':'NOT_APPLICABLE'}).select('*').single();if(error)return{ok:false as const,reason:'DB' as const};
 const staff:OfficeStaff={id:data.id,name:data.name,roleType:data.role_type,salaryMonthly:Number(data.salary_monthly_jr),technicalSkill:data.technical_skill,clientSkill:data.client_skill,productivity:data.productivity,loyalty:data.loyalty,status:'ACTIVE',hiredGameDate:data.hired_game_date,experience:data.experience||0,workload:data.workload||0,morale:data.morale??70,specialization:data.specialization||null,semester:data.semester||null,oabStatus:data.oab_status||'NOT_APPLICABLE'};const next={...s,staff:[...s.staff,staff]};cache(p,next);return{ok:true as const,state:next};
}
export async function depositOfficeCapital(p:PlayerProfile,amount:number){
 const s=readOfficeBusiness(p);const value=Math.max(0,Math.round(amount));if(!supabase||!p.cloudCareerId||!s.id||value<=0||p.money<value)return{ok:false as const};
 const balance=s.bankBalance+value;const {error}=await supabase.from('player_office_transactions').insert({office_business_id:s.id,game_date:date(p),transaction_type:'CAPITAL_IN',category:'OWNER_CAPITAL',amount:value,description:'Aporte do titular'});if(error)return{ok:false as const};
 await Promise.all([supabase.from('player_office_businesses').update({bank_balance:balance}).eq('id',s.id),supabase.from('careers').update({money:p.money-value}).eq('id',p.cloudCareerId)]);
 const next={...s,bankBalance:balance};cache(p,next);return{ok:true as const,state:next};
}
export async function fireOfficeStaff(p:PlayerProfile,id:string){const s=readOfficeBusiness(p);if(!supabase||!s.id)return false;const {error}=await supabase.from('player_office_staff').update({status:'TERMINATED'}).eq('id',id).eq('office_business_id',s.id);if(error)return false;cache(p,{...s,staff:s.staff.filter(x=>x.id!==id)});return true}
export async function settleOfficeMonth(p:PlayerProfile){const s=readOfficeBusiness(p);if(!supabase||!s.id)return{ok:false as const,reason:'CLOUD' as const};const month=`${p.gameCurrentYear}-${String(p.gameCurrentMonth).padStart(2,'0')}`;if(s.lastSettlementGameMonth===month)return{ok:false as const,reason:'PAID' as const};const cost=officeMonthlyCost(s);if(s.bankBalance<cost)return{ok:false as const,reason:'BALANCE' as const};const balance=s.bankBalance-cost;await supabase.from('player_office_transactions').insert({office_business_id:s.id,game_date:date(p),transaction_type:'EXPENSE',category:'MONTHLY_OPERATIONS',amount:cost,description:'Folha, imóvel e operação mensal',source_key:`monthly:${month}`});await supabase.from('player_office_businesses').update({bank_balance:balance,last_settlement_game_month:month}).eq('id',s.id);const next={...s,bankBalance:balance,lastSettlementGameMonth:month};cache(p,next);return{ok:true as const,state:next,cost}}
