import type{PlayerProfile,CareerTierId}from'../types/game';import{supabase}from'./supabase';
export type PublicOpportunityKind='JUDGE'|'PROSECUTOR'|'APPELLATE_PROMOTION'|'FIFTH_ADVOCACY';
export type PublicOpportunity={id:string;kind:PublicOpportunityKind;title:string;institution:string;announcementMonth:string;examMonth:string;fee:number;expiresMonth:string;status:'ANNOUNCED'|'ENROLLED'|'DECLINED';examType:string|null;targetTier:CareerTierId;requirements:string[]};
export type PublicCareerState={lastRollMonth:string|null;nextEligibleMonth:string|null;active:PublicOpportunity|null;history:Array<{id:string;kind:PublicOpportunityKind;status:string;month:string}>;legalPracticeMonths:number;lastPracticeMonth:string|null};
const P='rota_public_career_v1:';const empty=():PublicCareerState=>({lastRollMonth:null,nextEligibleMonth:null,active:null,history:[],legalPracticeMonths:0,lastPracticeMonth:null});
const key=(p:PlayerProfile)=>p.cloudCareerId||p.oabRegistration?.code||p.name||'player';const month=(p:PlayerProfile)=>p.gameCurrentYear*12+p.gameCurrentMonth-1;const monthKey=(n:number)=>Math.floor(n/12)+'-'+String(n%12+1).padStart(2,'0');
function cache(p:PlayerProfile,s:PublicCareerState){if(typeof window!=='undefined')localStorage.setItem(P+key(p),JSON.stringify(s))}
export function readPublicCareerState(p:PlayerProfile){let s=empty();if(typeof window!=='undefined')try{s={...s,...JSON.parse(localStorage.getItem(P+key(p))||'{}')}}catch{}return s}
async function persist(p:PlayerProfile,s:PublicCareerState){cache(p,s);if(supabase&&p.cloudCareerId){const{error}=await supabase.from('careers').update({public_career_opportunities:s,last_played_at:new Date().toISOString()}).eq('id',p.cloudCareerId);if(error)throw error}}
export async function hydratePublicCareerState(p:PlayerProfile){if(supabase&&p.cloudCareerId){const{data}=await supabase.from('careers').select('public_career_opportunities').eq('id',p.cloudCareerId).maybeSingle();if(data?.public_career_opportunities){const s={...empty(),...data.public_career_opportunities};cache(p,s);return s}}return readPublicCareerState(p)}
const practiceTiers=new Set<CareerTierId>(['ADVOGADO_HABILITADO','ADVOGADO_CONTRATADO','ADVOGADO_SENIOR','SOCIO_ESCRITORIO','DONO_ESCRITORIO']);
export async function reconcileLegalPractice(p:PlayerProfile){const s=readPublicCareerState(p),m=month(p),mk=monthKey(m);if(!p.oabRegistration||!practiceTiers.has(p.careerTier)||s.lastPracticeMonth===mk)return s;const next={...s,legalPracticeMonths:s.legalPracticeMonths+1,lastPracticeMonth:mk};await persist(p,next);return next}
function deterministicRoll(p:PlayerProfile,m:number){const seed=(p.name||'Rota').split('').reduce((a,c)=>a+c.charCodeAt(0),0);return(seed+m*37)%100}
function eligibleKinds(p:PlayerProfile,s:PublicCareerState):PublicOpportunityKind[]{const years=s.legalPracticeMonths/12;if(p.careerTier==='JUIZ_TITULAR')return['APPELLATE_PROMOTION'];if(years>=10&&practiceTiers.has(p.careerTier))return['JUDGE','PROSECUTOR','FIFTH_ADVOCACY'];if(years>=3&&practiceTiers.has(p.careerTier))return['JUDGE','PROSECUTOR'];return[]}
function build(p:PlayerProfile,s:PublicCareerState,kind:PublicOpportunityKind,m:number):PublicOpportunity{const id=kind+':'+monthKey(m);if(kind==='JUDGE')return{id,kind,title:'Concurso para Juiz de Direito Substituto',institution:'Tribunal de Justiça',announcementMonth:monthKey(m),examMonth:monthKey(m+3),expiresMonth:monthKey(m+1),fee:420,status:'ANNOUNCED',examType:'concurso_juiz',targetTier:'MAGISTRADO_SUBSTITUTO',requirements:['Bacharelado em Direito','3 anos de atividade jurídica','Aprovação nas etapas do concurso']};if(kind==='PROSECUTOR')return{id,kind,title:'Concurso para Promotor de Justiça',institution:'Ministério Público',announcementMonth:monthKey(m),examMonth:monthKey(m+3),expiresMonth:monthKey(m+1),fee:390,status:'ANNOUNCED',examType:'concurso_promotor',targetTier:'PROMOTOR_SUBSTITUTO',requirements:['Bacharelado em Direito','3 anos de atividade jurídica','Aprovação nas etapas do concurso']};if(kind==='FIFTH_ADVOCACY')return{id,kind,title:'Lista do Quinto Constitucional — Advocacia',institution:'Tribunal de Justiça / TRF',announcementMonth:monthKey(m),examMonth:monthKey(m+2),expiresMonth:monthKey(m+1),fee:0,status:'ANNOUNCED',examType:null,targetTier:'DESEMBARGADOR',requirements:['Mais de 10 anos de atividade profissional','Reputação e trajetória compatíveis','Processo de formação de lista e escolha']};return{id,kind,title:'Processo de promoção ao Tribunal',institution:'Tribunal de Justiça',announcementMonth:monthKey(m),examMonth:monthKey(m+2),expiresMonth:monthKey(m+1),fee:0,status:'ANNOUNCED',examType:null,targetTier:'DESEMBARGADOR',requirements:['Carreira na magistratura','Critérios de antiguidade/merecimento','Vaga disponível no tribunal']}}
export async function rollPublicCareerOpportunity(p:PlayerProfile){let s=await reconcileLegalPractice(p);const m=month(p),mk=monthKey(m);if(s.active||s.lastRollMonth===mk||(s.nextEligibleMonth&&s.nextEligibleMonth>mk))return s;const kinds=eligibleKinds(p,s),roll=deterministicRoll(p,m);s={...s,lastRollMonth:mk};if(kinds.length&&roll<24){const kind=kinds[roll%kinds.length];s.active=build(p,s,kind,m);s.nextEligibleMonth=monthKey(m+6)}await persist(p,s);return s}
export async function answerPublicOpportunity(p:PlayerProfile,accept:boolean){const s=readPublicCareerState(p);if(!s.active)return{ok:false as const,state:s,fee:0};if(accept&&p.money<s.active.fee)return{ok:false as const,state:s,fee:s.active.fee,reason:'MONEY' as const};const active={...s.active,status:accept?'ENROLLED' as const:'DECLINED' as const};const next={...s,active:accept?active:null,history:[{id:active.id,kind:active.kind,status:active.status,month:active.announcementMonth},...s.history].slice(0,50),nextEligibleMonth:monthKey(month(p)+(accept?4:6))};await persist(p,next);return{ok:true as const,state:next,fee:accept?active.fee:0,opportunity:active}}
export async function clearPublicOpportunity(p:PlayerProfile,id:string){const s=readPublicCareerState(p);if(s.active?.id!==id)return s;const next={...s,active:null};await persist(p,next);return next}