import type { PlayerProfile } from '../types/game';
import { getProfessionalOwnerKey, loadProfessionalProfile, saveProfessionalProfile } from './professionalRpg';

export type RelationshipEntityType = 'NPC' | 'ESTABLISHMENT' | 'ORGANIZATION';
export type RelationshipBond = 'UNKNOWN'|'ACQUAINTANCE'|'FRIEND'|'CLOSE_FRIEND'|'CASUAL_ROMANTIC'|'CASUAL_INTIMATE'|'DATING'|'PARTNER'|'MARRIED'|'AFFAIR'|'SECRET_AFFAIR'|'EX_PARTNER'|'RIVAL'|'ENEMY'|'PROFESSIONAL'|'CLIENT'|'FREQUENT_CUSTOMER';
export interface RelationshipDimensions { affinity:number;trust:number;intimacy:number;attraction:number;romance:number;commitment:number;conflict:number;professionalRespect:number;professionalTrust:number;rivalry:number;institutionalReputation:number;loyalty:number }
export type RelationshipDimension=keyof RelationshipDimensions;
export type RelationshipMemoryScope='PRIVATE'|'SOCIAL_CIRCLE'|'WORKPLACE'|'PROFESSIONAL_COMMUNITY'|'CITY'|'REGIONAL'|'NATIONAL';
export interface RelationshipMemory{id:string;kind:string;title:string;description:string;gameDate:string;intensity:number;scope:RelationshipMemoryScope;dimensions:Partial<RelationshipDimensions>}
export interface RelationshipRecord{entityId:string;entityType:RelationshipEntityType;name:string;role?:string;adultOnly:boolean;bonds:RelationshipBond[];dimensions:RelationshipDimensions;memories:RelationshipMemory[];interactionCount:number;lastInteractionDate?:string}
export interface RelationshipEngineState{version:1;records:Record<string,RelationshipRecord>}
const PREFIX='rota_relationship_engine_v1:'; const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
export const DEFAULT_RELATIONSHIP_DIMENSIONS:RelationshipDimensions={affinity:20,trust:15,intimacy:0,attraction:0,romance:0,commitment:0,conflict:0,professionalRespect:10,professionalTrust:10,rivalry:0,institutionalReputation:10,loyalty:5};
function key(player:Pick<PlayerProfile,'cloudCareerId'|'name'|'oabRegistration'>){return PREFIX+getProfessionalOwnerKey(player)}
export function seedCoreRelationships(player:any){const state=readRelationshipEngine(player);const core=[['MARIANA','Mariana Duarte','Secretária • Ramos & Associados'],['ROBERTO','Dr. Roberto Ramos','Sócio responsável'],['LAWYER_FELIPE','Dr. Felipe Martins','Advogado • colega de profissão'],['FRIEND_CARLOS','Carlos Nogueira','Amigo da época da faculdade']] as const;for(const [id,name,role] of core){if(!state.records['npc:'+id])state.records['npc:'+id]=baseRecord({entityId:'npc:'+id,entityType:'NPC',name,role,adultOnly:true})}if(hasCommittedPartner(player)&&player?.partnerName&&!state.records['npc:PARTNER']){const p=baseRecord({entityId:'npc:PARTNER',entityType:'NPC',name:player.partnerName,role:'Relacionamento pessoal',adultOnly:true},{affinity:65,trust:55,intimacy:65,romance:70,commitment:75});p.bonds=[player.relationshipStatus==='MARRIED'?'MARRIED':player.relationshipStatus==='STABLE_UNION'?'PARTNER':'DATING'];state.records[p.entityId]=p}return saveRelationshipEngine(player,state)}
function baseRecord(input:{entityId:string;entityType:RelationshipEntityType;name:string;role?:string;adultOnly?:boolean},seed:Partial<RelationshipDimensions>={}):RelationshipRecord{return{entityId:input.entityId,entityType:input.entityType,name:input.name,role:input.role,adultOnly:input.adultOnly!==false,bonds:[input.entityType==='NPC'?'ACQUAINTANCE':'FREQUENT_CUSTOMER'],dimensions:{...DEFAULT_RELATIONSHIP_DIMENSIONS,...seed},memories:[],interactionCount:0}}
export function readRelationshipEngine(player:any):RelationshipEngineState{try{const raw=localStorage.getItem(key(player));return raw?{version:1,records:JSON.parse(raw)?.records||{}}:{version:1,records:{}}}catch{return{version:1,records:{}}}}
export function saveRelationshipEngine(player:any,state:RelationshipEngineState){try{localStorage.setItem(key(player),JSON.stringify(state));window.dispatchEvent(new CustomEvent('rota:relationships-updated',{detail:state}))}catch{}return state}
export function relationshipRecord(state:RelationshipEngineState,input:{entityId:string;entityType:RelationshipEntityType;name:string;role?:string;adultOnly?:boolean}){return state.records[input.entityId]||baseRecord(input)}
export function ensureRelationship(player:any,input:{entityId:string;entityType:RelationshipEntityType;name:string;role?:string;adultOnly?:boolean;bond?:RelationshipBond}){const state=readRelationshipEngine(player);if(state.records[input.entityId])return state;const record=baseRecord(input);if(input.bond)record.bonds=[input.bond];state.records[input.entityId]=record;return saveRelationshipEngine(player,state)}
export function applyRelationshipInteraction(player:any,input:{entityId:string;entityType:RelationshipEntityType;name:string;role?:string;gameDate:string;kind:string;title:string;description:string;scope?:RelationshipMemoryScope;intensity?:number;dimensions:Partial<RelationshipDimensions>;bond?:RelationshipBond;adultOnly?:boolean}){
 const state=readRelationshipEngine(player);const current=relationshipRecord(state,input);const dimensions={...current.dimensions};for(const [dimension,delta] of Object.entries(input.dimensions)){const d=dimension as RelationshipDimension;dimensions[d]=clamp(dimensions[d]+(Number(delta)||0))}
 const bonds=[...current.bonds];if(input.bond&&!bonds.includes(input.bond))bonds.push(input.bond);const memory:RelationshipMemory={id:`rel-${input.entityId}-${Date.now()}`,kind:input.kind,title:input.title,description:input.description,gameDate:input.gameDate,intensity:Math.max(1,Math.min(100,input.intensity||20)),scope:input.scope||'PRIVATE',dimensions:input.dimensions};
 state.records[input.entityId]={...current,name:input.name,role:input.role||current.role,adultOnly:input.adultOnly!==false,bonds,dimensions,memories:[memory,...current.memories].slice(0,60),interactionCount:current.interactionCount+1,lastInteractionDate:input.gameDate};return saveRelationshipEngine(player,state)
}
export function hasCommittedPartner(player:any){return player?.relationshipStatus==='DATING'||player?.relationshipStatus==='MARRIED'||player?.relationshipStatus==='STABLE_UNION'}
export function classifyRomanticBond(player:any,intimate=false):RelationshipBond{return hasCommittedPartner(player)?'SECRET_AFFAIR':intimate?'CASUAL_INTIMATE':'CASUAL_ROMANTIC'}
export function relationshipEthicsPenalty(player:any,bond:RelationshipBond){if(!hasCommittedPartner(player))return 0;return bond==='AFFAIR'||bond==='SECRET_AFFAIR'?-2:0}
export function canAttemptRomanticInteraction(r:RelationshipRecord){return r.adultOnly&&r.entityType==='NPC'&&r.dimensions.affinity>=30&&r.dimensions.trust>=20}
export function canAttemptIntimateInteraction(r:RelationshipRecord){return r.adultOnly&&r.entityType==='NPC'&&r.dimensions.attraction>=45&&r.dimensions.trust>=35&&r.dimensions.intimacy>=30}
export function relationshipLabel(r:RelationshipRecord){if(r.bonds.includes('SECRET_AFFAIR'))return'Caso secreto';if(r.bonds.includes('AFFAIR'))return'Caso extraconjugal';if(r.bonds.includes('MARRIED'))return'Casamento';if(r.bonds.includes('PARTNER'))return'Relacionamento duradouro';if(r.bonds.includes('DATING'))return'Namoro';if(r.bonds.includes('CASUAL_INTIMATE'))return'Relação íntima casual';if(r.bonds.includes('CASUAL_ROMANTIC'))return'Encontros casuais';if(r.bonds.includes('RIVAL'))return'Rivalidade';if(r.dimensions.affinity>=70)return'Muito próximo';if(r.dimensions.affinity>=45)return'Boa relação';return r.entityType==='NPC'?'Conhecido':'Cliente'}
export const RELATIONSHIP_BOND_LABELS:Record<RelationshipBond,string>={UNKNOWN:'Desconhecido',ACQUAINTANCE:'Conhecido',FRIEND:'Amizade',CLOSE_FRIEND:'Amizade próxima',CASUAL_ROMANTIC:'Encontros casuais',CASUAL_INTIMATE:'Relação íntima casual',DATING:'Namoro',PARTNER:'Relacionamento duradouro',MARRIED:'Casamento',AFFAIR:'Caso extraconjugal',SECRET_AFFAIR:'Caso secreto',EX_PARTNER:'Ex-parceiro(a)',RIVAL:'Rivalidade',ENEMY:'Inimizade',PROFESSIONAL:'Relação profissional',CLIENT:'Cliente',FREQUENT_CUSTOMER:'Cliente frequente'};

export type RomanticAction='FLIRT'|'DATE'|'INTIMATE'|'COMMIT'|'BREAK_UP'|'CONFESS_AFFAIR';
export interface RomanticActionResult{ok:boolean;message:string;bond?:RelationshipBond;ethicsDelta:number;characterDelta:number}
export function performRomanticAction(player:PlayerProfile,entityId:string,action:RomanticAction,gameDate:string):RomanticActionResult{
 const state=readRelationshipEngine(player),r=state.records[entityId];if(!r||r.entityType!=='NPC')return{ok:false,message:'Pessoa indisponível.',ethicsDelta:0,characterDelta:0};
 if(!r.adultOnly)return{ok:false,message:'Interação romântica indisponível.',ethicsDelta:0,characterDelta:0};
 let dims:Partial<RelationshipDimensions>={},bond:RelationshipBond|undefined,title='',description='',ethicsDelta=0,characterDelta=0;
 if(action==='FLIRT'){if(r.dimensions.affinity<30)return{ok:false,message:'Ainda não existe afinidade suficiente.',ethicsDelta:0,characterDelta:0};dims={attraction:8,romance:5,affinity:2};title='Flertou';description='A conversa ganhou um tom romântico.'}
 if(action==='DATE'){if(!canAttemptRomanticInteraction(r))return{ok:false,message:'Confiança ou afinidade insuficiente.',ethicsDelta:0,characterDelta:0};bond=classifyRomanticBond(player,false);dims={romance:10,intimacy:6,attraction:6,affinity:4};title='Encontro romântico';description='Vocês passaram um tempo juntos em um encontro.'}
 if(action==='INTIMATE'){if(!canAttemptIntimateInteraction(r))return{ok:false,message:'A relação ainda não possui intimidade e confiança suficientes.',ethicsDelta:0,characterDelta:0};bond=classifyRomanticBond(player,true);dims={intimacy:12,romance:6,commitment:2};title='Momento íntimo';description='A relação avançou para maior intimidade.'}
 if(action==='COMMIT'){if(r.dimensions.romance<55||r.dimensions.trust<45)return{ok:false,message:'A relação ainda não está pronta para compromisso.',ethicsDelta:0,characterDelta:0};if(hasCommittedPartner(player)&&entityId!=='npc:PARTNER')return{ok:false,message:'Encerre o relacionamento atual antes de assumir outro compromisso.',ethicsDelta:0,characterDelta:0};bond='DATING';dims={commitment:15,loyalty:8,romance:5};title='Início de namoro';description='Vocês decidiram assumir um relacionamento.'}
 if(action==='BREAK_UP'){bond='EX_PARTNER';dims={commitment:-35,romance:-20,conflict:8};title='Término';description='O relacionamento foi encerrado.'}
 if(action==='CONFESS_AFFAIR'){dims={trust:-30,loyalty:-35,conflict:35,romance:-15};title='Confissão de traição';description='A infidelidade foi revelada e abalou profundamente a confiança.'}
 if(bond==='SECRET_AFFAIR'||bond==='AFFAIR'){ethicsDelta=-1;characterDelta=-2}
 applyRelationshipInteraction(player,{entityId:r.entityId,entityType:'NPC',name:r.name,role:r.role,gameDate,kind:action,title,description,scope:bond==='SECRET_AFFAIR'?'PRIVATE':'SOCIAL_CIRCLE',intensity:bond==='SECRET_AFFAIR'?55:30,dimensions:dims,bond,adultOnly:true});
 if(ethicsDelta||characterDelta){const p=loadProfessionalProfile(player);if(p)saveProfessionalProfile(player,{...p,ethics:clamp(p.ethics+ethicsDelta),character:clamp(p.character+characterDelta)})}
 return{ok:true,message:description,bond,ethicsDelta,characterDelta};
}
