import type {PlayerProfile} from '../types/game';
import {applyRelationshipInteraction,readRelationshipEngine,type RelationshipMemoryScope} from './relationshipEngine';
import {supabase} from './supabase';
export interface WorldMemoryInput{memoryKey:string;kind:string;title:string;description:string;scope:Exclude<RelationshipMemoryScope,'PRIVATE'|'SOCIAL_CIRCLE'>;intensity:number;sourceCaseId?:string;respectDelta?:number;trustDelta?:number;rivalryDelta?:number}
const date=(p:PlayerProfile)=>[p.gameCurrentYear,String(p.gameCurrentMonth).padStart(2,'0'),String(p.gameCurrentDay).padStart(2,'0')].join('-');
const reaches=(scope:WorldMemoryInput['scope'],role:string)=>{const r=role.toLowerCase();if(scope==='NATIONAL')return true;if(scope==='REGIONAL')return !r.includes('amigo');if(scope==='CITY')return true;if(scope==='PROFESSIONAL_COMMUNITY')return /(advog|sócio|juiz|promotor|desembarg|defensor|perit|oficial|servid|escriv|oab|tribunal)/i.test(r);return /(ramos|secret|colega|advog)/i.test(r)};
export async function applyWorldMemoryEvent(p:PlayerProfile,input:WorldMemoryInput){
 const state=readRelationshipEngine(p);const targets=Object.values(state.records).filter(r=>r.entityType==='NPC'&&reaches(input.scope,r.role||''));for(const r of targets){const duplicate=r.memories.some(m=>m.kind===input.kind&&m.title===input.title&&m.gameDate===date(p));if(duplicate)continue;applyRelationshipInteraction(p,{entityId:r.entityId,entityType:'NPC',name:r.name,role:r.role,gameDate:date(p),kind:input.kind,title:input.title,description:input.description,scope:input.scope,intensity:input.intensity,dimensions:{professionalRespect:input.respectDelta||0,professionalTrust:input.trustDelta||0,rivalry:input.rivalryDelta||0,institutionalReputation:Math.round((input.respectDelta||0)/2)},bond:'PROFESSIONAL'});
 }
 if(!supabase||!p.cloudCareerId)return{targets:targets.length};const {data:user}=await supabase.auth.getUser();if(!user.user)return{targets:targets.length};for(const r of targets){await supabase.from('career_world_memories').upsert({career_id:p.cloudCareerId,user_id:user.user.id,memory_key:input.memoryKey,entity_key:r.entityId,entity_name:r.name,entity_role:r.role||null,kind:input.kind,title:input.title,description:input.description,game_date:date(p),scope:input.scope,intensity:input.intensity,respect_delta:input.respectDelta||0,trust_delta:input.trustDelta||0,rivalry_delta:input.rivalryDelta||0,source_case_id:input.sourceCaseId||null},{onConflict:'career_id,memory_key,entity_key'})}return{targets:targets.length};
}
export async function hydrateWorldMemories(p:PlayerProfile){
 if(!supabase||!p.cloudCareerId)return 0;const {data}=await supabase.from('career_world_memories').select('*').eq('career_id',p.cloudCareerId).order('game_date',{ascending:true});let restored=0;for(const x of data||[]){const state=readRelationshipEngine(p);const r=state.records[x.entity_key];if(!r||r.memories.some(m=>m.kind===x.kind&&m.title===x.title&&m.gameDate===x.game_date))continue;applyRelationshipInteraction(p,{entityId:x.entity_key,entityType:'NPC',name:x.entity_name,role:x.entity_role||undefined,gameDate:x.game_date,kind:x.kind,title:x.title,description:x.description,scope:x.scope,intensity:x.intensity,dimensions:{professionalRespect:x.respect_delta,professionalTrust:x.trust_delta,rivalry:x.rivalry_delta,institutionalReputation:Math.round(x.respect_delta/2)},bond:'PROFESSIONAL'});restored++}return restored;
}
export function getNpcMemoryContext(p:PlayerProfile,entityId:string){const r=readRelationshipEngine(p).records[entityId];if(!r)return null;const important=r.memories.filter(m=>m.intensity>=35||['PROFESSIONAL_COMMUNITY','CITY','REGIONAL','NATIONAL'].includes(m.scope)).slice(0,5);return{name:r.name,role:r.role,respect:r.dimensions.professionalRespect,trust:r.dimensions.professionalTrust,rivalry:r.dimensions.rivalry,memories:important,reaction:r.dimensions.rivalry>=60?'HOSTILE':r.dimensions.professionalRespect>=70?'RESPECTFUL':r.dimensions.professionalTrust>=60?'TRUSTING':'NEUTRAL'} as const}