import React,{useEffect,useMemo,useState}from'react';
import{Building2,Heart,History,ShieldCheck,Users,X,BriefcaseBusiness}from'lucide-react';
import type{PlayerProfile}from'../../types/game';
import{RELATIONSHIP_BOND_LABELS,performRomanticAction,readRelationshipEngine,relationshipLabel,type RelationshipRecord,type RomanticAction}from'../../lib/relationshipEngine';
import{persistRelationshipEngine,syncRelationshipEngine}from'../../lib/relationshipRepository';
import styles from'./RelationshipCenter.module.css';
export const OPEN_RELATIONSHIP_CENTER_EVENT='rota:open-relationship-center';
const bars:[keyof RelationshipRecord['dimensions'],string][]=[['affinity','Afinidade'],['trust','Confiança'],['intimacy','Intimidade'],['attraction','Atração'],['romance','Romance'],['commitment','Compromisso'],['conflict','Conflito'],['professionalRespect','Respeito profissional'],['professionalTrust','Confiança profissional'],['rivalry','Rivalidade'],['institutionalReputation','Reputação institucional'],['loyalty','Lealdade']];
const scopeLabels:any={PRIVATE:'Privado',SOCIAL_CIRCLE:'Círculo social',WORKPLACE:'Ambiente de trabalho',PROFESSIONAL_COMMUNITY:'Comunidade profissional',CITY:'Cidade',REGIONAL:'Regional',NATIONAL:'Nacional'};
export function RelationshipCenter({player}:{player:PlayerProfile}){
 const[open,setOpen]=useState(false),[tick,setTick]=useState(0),[filter,setFilter]=useState<'ALL'|'NPC'|'ESTABLISHMENT'|'ORGANIZATION'>('ALL'),[selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{void syncRelationshipEngine(player).then(()=>setTick(v=>v+1));},[player.cloudCareerId]);
 useEffect(()=>{const show=()=>setOpen(true),refresh=()=>setTick(v=>v+1);window.addEventListener(OPEN_RELATIONSHIP_CENTER_EVENT,show);window.addEventListener('rota:relationships-updated',refresh);return()=>{window.removeEventListener(OPEN_RELATIONSHIP_CENTER_EVENT,show);window.removeEventListener('rota:relationships-updated',refresh)}},[]);
 const records=useMemo(()=>Object.values(readRelationshipEngine(player).records).sort((a,b)=>b.interactionCount-a.interactionCount||b.dimensions.affinity-a.dimensions.affinity),[player,tick,open]);
 const visible=records.filter(r=>filter==='ALL'||r.entityType===filter),current=records.find(r=>r.entityId===selected&&visible.includes(r))||visible[0];
 if(!open)return <button className={styles.launcher} onClick={()=>setOpen(true)} title="Abrir relacionamentos"><Users size={17}/><span>Relacionamentos</span></button>;
 return <div className={styles.backdrop}><section className={styles.modal}>
 <header className={styles.header}><div className={styles.titleIcon}><Users size={20}/></div><div className={styles.title}><span>Vida pessoal • networking • reputação</span><h2>Relacionamentos</h2><p>Sua rede de pessoas, vínculos profissionais e lugares que fazem parte da sua história.</p></div><button className={styles.close} onClick={()=>setOpen(false)}><X size={18}/></button></header>
 <nav className={styles.tabs}><button onClick={()=>setFilter('ALL')} className={filter==='ALL'?styles.active:''}>Todos <b>{records.length}</b></button><button onClick={()=>setFilter('NPC')} className={filter==='NPC'?styles.active:''}><Heart size={14}/>Pessoas <b>{records.filter(r=>r.entityType==='NPC').length}</b></button><button onClick={()=>setFilter('ESTABLISHMENT')} className={filter==='ESTABLISHMENT'?styles.active:''}><Building2 size={14}/>Estabelecimentos <b>{records.filter(r=>r.entityType==='ESTABLISHMENT').length}</b></button><button onClick={()=>setFilter('ORGANIZATION')} className={filter==='ORGANIZATION'?styles.active:''}><BriefcaseBusiness size={14}/>Organizações <b>{records.filter(r=>r.entityType==='ORGANIZATION').length}</b></button></nav>
 <div className={styles.layout}><aside className={styles.contacts}>{visible.length?visible.map(r=><button key={r.entityId} className={current?.entityId===r.entityId?styles.selected:''} onClick={()=>setSelected(r.entityId)}><div className={styles.avatar}>{r.entityType==='NPC'?<Heart size={15}/>:<Building2 size={15}/>}</div><div><strong>{r.name}</strong><span>{r.role||relationshipLabel(r)}</span><small>{relationshipLabel(r)} • {r.interactionCount} interações</small></div></button>):<div className={styles.empty}><Users size={26}/><strong>Nenhum vínculo nesta categoria</strong><p>Novos contatos surgem naturalmente em eventos, trabalho e estabelecimentos.</p></div>}</aside>
 <main className={styles.detail}>{current?<><div className={styles.identity}><div className={styles.bigAvatar}>{current.entityType==='NPC'?<Heart size={22}/>:<Building2 size={22}/>}</div><div><span>{current.entityType==='NPC'?'Pessoa':'Estabelecimento'}</span><h3>{current.name}</h3><p>{current.role||relationshipLabel(current)}</p></div><strong className={styles.status}>{relationshipLabel(current)}</strong></div>
 <div className={styles.bonds}>{current.bonds.map(b=><span key={b}>{RELATIONSHIP_BOND_LABELS[b]}</span>)}</div>
 <section><div className={styles.sectionTitle}><BriefcaseBusiness size={15}/><div><strong>{current.entityType==='NPC'?'Como está esta relação':'Relacionamento com o local'}</strong><span>Dimensões independentes que evoluem com acontecimentos.</span></div></div><div className={styles.metrics}>{bars.filter(([k])=>current.entityType==='NPC'||['trust','institutionalReputation','loyalty'].includes(k)).map(([k,label])=><div key={k}><div><span>{label}</span><strong>{current.dimensions[k]}/100</strong></div><i><b style={{width:`${current.dimensions[k]}%`}}/></i></div>)}</div></section>
 {current.entityType==='NPC'&&<section><div className={styles.sectionTitle}><Heart size={15}/><div><strong>Interações pessoais</strong><span>As opções dependem da confiança, afinidade e história construída.</span></div></div><div className={styles.bonds}>{([['FLIRT','Flertar'],['DATE','Convidar para encontro'],['INTIMATE','Aproximar intimamente'],['COMMIT','Assumir namoro'],['BREAK_UP','Encerrar relação']] as [RomanticAction,string][]).map(([action,label])=><button key={action} onClick={async()=>{const d=`${player.gameCurrentYear}-${String(player.gameCurrentMonth).padStart(2,'0')}-${String(player.gameCurrentDay).padStart(2,'0')}`;const result=performRomanticAction(player,current.entityId,action,d);if(result.ok){await persistRelationshipEngine(player);setTick(v=>v+1)}else window.alert(result.message)}}>{label}</button>)}</div></section>}
 <section className={styles.memories}><div className={styles.sectionTitle}><History size={15}/><div><strong>Memórias e acontecimentos</strong><span>O histórico explica por que a relação chegou ao estado atual.</span></div></div>{current.memories.length?current.memories.slice(0,12).map(m=><article key={m.id}><div><strong>{m.title}</strong><span>{m.gameDate} • {scopeLabels[m.scope]}</span></div><p>{m.description}</p></article>):<div className={styles.emptyMemory}>Este vínculo já existe, mas ainda não possui acontecimentos registrados no novo motor.</div>}</section>
 {current.entityType==='NPC'&&<div className={styles.notice}><ShieldCheck size={17}/><span>Vida pessoal e atuação profissional são avaliadas separadamente. Afinidade com agentes públicos não concede vantagem automática em processos.</span></div>}</>:<div className={styles.emptyDetail}><Users size={34}/><h3>Sua rede começa com a história do personagem</h3><p>Contatos anteriores são importados da vida social e novas relações aparecem conforme você joga.</p></div>}</main></div></section></div>
}