import React,{useEffect,useMemo,useState} from 'react';
import type {PlayerProfile} from '../types/game';
import {Building,Users,Coins,X,MapPin,Briefcase} from 'lucide-react';
import {sound} from '../utils/sound';
import {acquireCommercialProperty,fireOfficeStaff,generateOfficeCandidates,hireOfficeCandidate,hydrateOfficeBusiness,loadCommercialProperties,officeMonthlyCost,readOfficeBusiness,settleOfficeMonth,type CommercialProperty,type OfficeBusinessState} from '../lib/officeBusiness';

interface Props{isOpen:boolean;onClose:()=>void;player:PlayerProfile;onHireEmployee?:(e:any)=>void;onFireEmployee?:(id:string)=>void;onPayOfficeExpenses?:()=>void}
const money=(n:number|null|undefined)=>`JR$ ${Number(n||0).toLocaleString('pt-BR')}`;
const roleLabel=(r:string)=>({INTERN:'Estagiário',ASSISTANT:'Assistente',JUNIOR_LAWYER:'Advogado Júnior',MID_LAWYER:'Advogado Pleno',SENIOR_LAWYER:'Advogado Sênior'}[r]||r);

export const OfficeManagementModal:React.FC<Props>=({isOpen,onClose,player})=>{
 const [state,setState]=useState<OfficeBusinessState>(()=>readOfficeBusiness(player));const [properties,setProperties]=useState<CommercialProperty[]>([]);const [tab,setTab]=useState<'estrutura'|'financeiro'|'equipe'>('estrutura');const [officeName,setOfficeName]=useState(player.officeFinances?.officeName||`${player.name||'Meu'} Advocacia`);const [notice,setNotice]=useState('');
 useEffect(()=>{if(!isOpen)return;void hydrateOfficeBusiness(player).then(setState);void loadCommercialProperties(player).then(setProperties)},[isOpen,player]);
 const candidates=useMemo(()=>generateOfficeCandidates(player,state),[player,state]);if(!isOpen)return null;
 const acquire=async(p:CommercialProperty,mode:'RENT'|'OWNED')=>{setNotice('');const r=await acquireCommercialProperty(player,p,mode,officeName.trim());if(!r.ok){setNotice(r.reason==='MONEY'?'Patrimônio pessoal insuficiente para entrada/compra.':'Não foi possível formalizar o escritório. Confira a migration e sua conexão.');return}setState(r.state);setNotice(`Escritório constituído. Investimento inicial: ${money(r.upfront)}.`)};
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0A0A0B]/90 p-4"><div className="flex max-h-[92vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl border border-[#2A2A2E] bg-[#111113] text-[#E0E0E0]">
  <header className="flex items-center justify-between border-b border-[#2A2A2E] p-5"><div><h2 className="flex items-center gap-2 font-serif text-xl font-bold"><Building className="text-[#C5A059]"/>Escritório próprio</h2><p className="text-xs text-[#888]">Imóvel, constituição, caixa empresarial e equipe.</p></div><button onClick={onClose}><X/></button></header>
  <div className="grid grid-cols-2 gap-2 border-b border-[#2A2A2E] p-4 sm:grid-cols-4"><K label="Status" value={state.status}/><K label="Caixa empresarial" value={money(state.bankBalance)}/><K label="Equipe" value={String(state.staff.length)}/><K label="Custo mensal" value={money(officeMonthlyCost(state))}/></div>
  <nav className="flex gap-2 border-b border-[#2A2A2E] p-3">{(['estrutura','financeiro','equipe'] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg px-4 py-2 text-xs font-bold uppercase ${tab===x?'bg-[#C5A059] text-black':'bg-[#1A1A1D] text-[#AAA]'}`}>{x}</button>)}</nav>
  <main className="flex-1 overflow-y-auto p-5">
   {notice&&<div className="mb-4 rounded-xl border border-[#C5A059]/30 bg-[#C5A059]/10 p-3 text-xs text-[#D9C38C]">{notice}</div>}
   {tab==='estrutura'&&<div className="space-y-4">{state.status!=='ACTIVE'?<><div className="rounded-xl border border-[#2A2A2E] bg-[#161618] p-4"><label className="text-xs text-[#AAA]">Nome profissional</label><input value={officeName} onChange={e=>setOfficeName(e.target.value)} className="mt-2 w-full rounded-lg border border-[#333] bg-[#0D0D0E] p-3 text-sm"/></div><h3 className="text-xs font-bold uppercase text-[#888]">Imóveis oferecidos pelas imobiliárias do Rota Admin</h3>{properties.length===0?<p className="rounded-xl border border-dashed border-[#333] p-5 text-xs text-[#777]">Nenhum imóvel comercial publicado. Cadastre uma imobiliária (IMOBILIARIA) e imóveis comerciais no Rota Admin.</p>:properties.map(p=><div key={p.id} className="rounded-xl border border-[#2A2A2E] bg-[#161618] p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{p.title}</b><p className="mt-1 text-xs text-[#888]"><MapPin size={12} className="inline"/> {p.address} • {p.areaM2}m² • {p.roomCount} sala(s) • capacidade {p.capacity}</p><p className="mt-1 text-[11px] text-[#C5A059]">{p.realtorName}</p></div><div className="flex gap-2">{p.rentMonthly!=null&&<button onClick={()=>void acquire(p,'RENT')} className="rounded-lg bg-[#C5A059] px-3 py-2 text-xs font-bold text-black">Alugar {money(p.rentMonthly)}/mês</button>}{p.salePrice!=null&&<button onClick={()=>void acquire(p,'OWNED')} className="rounded-lg border border-[#C5A059] px-3 py-2 text-xs font-bold text-[#C5A059]">Comprar {money(p.salePrice)}</button>}</div></div></div>)}</>:<div className="rounded-xl border border-[#2A2A2E] bg-[#161618] p-5"><b>{state.officeName}</b><p className="mt-2 text-xs text-[#AAA]">{state.occupancyType==='RENT'?'Imóvel alugado':'Imóvel próprio'} • {state.property?.title} • capacidade {state.property?.capacity}</p><p className="mt-1 text-xs text-[#777]">{state.property?.address}</p></div>}</div>}
   {tab==='financeiro'&&<div className="space-y-4"><div className="rounded-xl border border-[#2A2A2E] bg-[#161618] p-5"><Coins className="mb-2 text-[#34D399]"/><b>Caixa empresarial: {money(state.bankBalance)}</b><p className="mt-2 text-xs text-[#888]">O caixa do escritório é separado do patrimônio pessoal. Folha, imóvel e operação são liquidados aqui.</p><p className="mt-2 text-xs">Custo operacional atual: <b>{money(officeMonthlyCost(state))}/mês</b></p><button onClick={async()=>{const r=await settleOfficeMonth(player);if(r.ok){setState(r.state);setNotice(`Despesas mensais liquidadas: ${money(r.cost)}.`)}else setNotice(r.reason==='PAID'?'Este mês já foi liquidado.':r.reason==='BALANCE'?'Caixa empresarial insuficiente.':'Liquidação indisponível.')}} className="mt-4 rounded-lg bg-[#C5A059] px-4 py-2 text-xs font-bold text-black">Liquidar mês</button></div></div>}
   {tab==='equipe'&&<div className="space-y-4"><h3 className="text-xs font-bold uppercase text-[#888]">Equipe ativa</h3>{state.staff.map(s=><div key={s.id} className="flex justify-between rounded-xl border border-[#2A2A2E] bg-[#161618] p-3 text-xs"><span><b>{s.name}</b> • {roleLabel(s.roleType)} • técnica {s.technicalSkill} • clientes {s.clientSkill}</span><button onClick={async()=>{if(await fireOfficeStaff(player,s.id))setState(readOfficeBusiness(player))}} className="text-[#F87171]">Demitir</button></div>)}<h3 className="pt-3 text-xs font-bold uppercase text-[#888]"><Briefcase size={13} className="inline"/> Processo seletivo • candidatos do dia</h3>{state.status!=='ACTIVE'?<p className="text-xs text-[#777]">Constitua o escritório antes de contratar.</p>:candidates.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#2A2A2E] bg-[#161618] p-4 text-xs"><div><b>{c.name}</b><p className="text-[#888]">{roleLabel(c.roleType)} • técnica {c.technicalSkill} • clientes {c.clientSkill} • produtividade {c.productivity}</p><p>{money(c.salaryMonthly)}/mês</p></div><button onClick={async()=>{const r=await hireOfficeCandidate(player,c);if(r.ok)setState(r.state);else setNotice(r.reason==='CAPACITY'?'O imóvel atingiu sua capacidade física.':'Não foi possível contratar.')}} className="rounded-lg bg-[#C5A059] px-3 py-2 font-bold text-black"><Users size={13} className="inline"/> Contratar</button></div>)}</div>}
  </main><footer className="border-t border-[#2A2A2E] p-4 text-right"><button onClick={()=>{sound.playClick();onClose()}} className="rounded-lg bg-[#1A1A1D] px-4 py-2 text-xs">Fechar</button></footer>
 </div></div>
}
function K({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#2A2A2E] bg-[#161618] p-3 text-center"><span className="block text-[9px] uppercase text-[#777]">{label}</span><b className="text-xs text-[#C5A059]">{value}</b></div>}
