-- Seed 46º EOU 2026 Tipo 1 - questões 41 a 50
begin;

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',41,'Direito Civil','Eduardo vendeu um imóvel urbano a Clara, estipulando em contrato particular que, caso futuramente ela decidisse vendê-lo, Clara deveria notificá-lo previamente, conferindo-lhe o direito de adquirir o bem nas mesmas condições ofertadas a terceiros. Passados doze meses da compra, Clara recebeu proposta de venda pelo mesmo valor pago e, sem notificar Eduardo, vendeu o imóvel para Flávio. Eduardo, ao saber do negócio já concluído, procurou Flávio para discutir o direito de preferência, mas este afirmou não ter sido informado sobre qualquer cláusula contratual anterior. Eduardo ajuizou ação para haver o imóvel para si, mediante o pagamento do mesmo valor da proposta aceita por Clara. Com base nas disposições legais sobre o direito de preempção, assinale a afirmativa correta.','[{"id":"A","text":"Eduardo não pode exigir o imóvel para si, mas poderá pleitear perdas e danos contra Clara, caso comprove que foi privado de exercer seu direito de preferência."},{"id":"B","text":"Eduardo poderá reaver o imóvel se provar que notificou Flávio, por escrito, antes da conclusão do negócio, mesmo que Clara tenha omitido a existência da preferência."},{"id":"C","text":"Eduardo perdeu o direito à preempção, pois este não pode ser exercido se o novo comprador não tinha ciência da cláusula de preferência existente no contrato anterior."},{"id":"D","text":"Eduardo pode exigir o imóvel para si, mediante depósito do valor ajustado com o terceiro, desde que o faça no prazo de até 180 dias da alienação, conforme admite o Código Civil."}]'::jsonb,'A','oficial',41,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":41}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',42,'Direito Civil','Sara, em 24 de outubro de 2023, outorgou a Vítor, seu filho, uma procuração por instrumento público para vender seu imóvel até 24 de outubro de 2026. No momento da outorga, Sara gozava de boa saúde mental. A partir de 2024, Sara passou a sofrer um acelerado processo de demência, vindo a perder as suas habilidades cognitivas básicas no início de 2025. Sara foi interditada e Roberto, seu marido, tornou-se o seu curador. Em 24 de setembro de 2025, Raul se interessou em comprar o imóvel de Sara, e Vítor se apresentou como procurador da mãe. Na qualidade de advogado de Raul, assinale a opção que apresenta a sua orientação jurídica para o caso.','[{"id":"A","text":"Não recomendaria a aquisição do imóvel, figurando Vítor como representante de Sara, pois há possíveis interesses conflitantes entre eles."},{"id":"B","text":"Não recomendaria a aquisição do imóvel, figurando Vítor como representante de Sara, pois, diante da interdição, o contrato de mandato é extinto."},{"id":"C","text":"Recomendaria a aquisição do imóvel, figurando Vítor como representante de Sara, pois, apesar da incapacidade superveniente, o contrato de mandato é eficaz até o término do prazo, quando este for determinado."},{"id":"D","text":"Recomendaria a aquisição do imóvel, figurando Vítor como representante de Sara, pois, tendo a procuração sido outorgada por instrumento público, e estando Sara com boa saúde mental no momento da outorga, o mandato é válido e eficaz."}]'::jsonb,'B','oficial',42,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":42}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',43,'Direito da Criança e do Adolescente','Enzo, de 16 anos de idade, ingressou em um grande supermercado e subtraiu diversas peças de picanha, que totalizaram mais de R$ 2.000,00 (dois mil reais). Um segurança, percebendo a atitude suspeita de Enzo, o apreendeu no estacionamento. Enzo confessou a autoria. O Ministério Público representou contra o adolescente pela prática de ato infracional análogo ao crime de furto (Art. 155, caput, do CP). Durante a instrução processual, ficou constatado que essa foi a primeira passagem de Enzo pela Vara da Infância e Juventude. A família de Enzo procurou você, como advogado(a), para saber qual medida poderá ser aplicada ao caso. Com base na expressa disposição do Estatuto da Criança e do Adolescente (ECA), assinale a afirmativa que apresenta, corretamente, a medida que você indicou.','[{"id":"A","text":"Não poderá ser aplicada a medida socioeducativa de advertência, tendo em vista a primariedade e a pouca lesividade do ato."},{"id":"B","text":"Ele deve receber a medida socioeducativa de internação, já que isso o afastará do meio criminoso e permitirá sua ressocialização."},{"id":"C","text":"A medida cabível é a semiliberdade, já que ele deve receber uma medida socioeducativa, mas não a ponto de mantê-lo totalmente privado de liberdade."},{"id":"D","text":"Não cabe a aplicação da medida socioeducativa de internação, porque o ato não foi cometido mediante grave ameaça ou violência à pessoa e não há reiteração em infrações graves."}]'::jsonb,'D','oficial',43,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":43}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',44,'Direito da Criança e do Adolescente','Matheus, 17 anos, insiste em passar longos períodos na rua, deixando de lado os deveres escolares e, também, os compromissos familiares. A rebeldia de Matheus é atribuída à ausência do pai, que abandonou a família logo após o seu nascimento e de quem nunca mais ele teve notícia. Carolina, preocupada com a situação do filho, busca a inserção de Matheus no mercado formal de trabalho e encontra a oportunidade em um grande supermercado da região. O estabelecimento necessita de uma pessoa para carregar as caixas de produtos e abastecer o mercado durante a madrugada, especificamente entre meia-noite e quatro horas da manhã. Entretanto, por ainda não ter atingido a maioridade, Carolina possui dúvidas sobre a possibilidade de Matheus trabalhar. Por isso, procura você, como advogado(a), para ter sua orientação jurídica. Sobre a hipótese apresentada, assinale a afirmativa que, corretamente, apresenta a sua orientação.','[{"id":"A","text":"Matheus, por estar no final da adolescência, pode trabalhar sem restrições."},{"id":"B","text":"Matheus não pode ingressar no mercado formal de trabalho, por ainda não ter completado 18 anos."},{"id":"C","text":"Matheus não pode trabalhar no cargo oferecido, já que o ECA veda o trabalho noturno entre as 22h de um dia e as 5h do dia seguinte."},{"id":"D","text":"Por ter 17 anos, Matheus pode trabalhar no mercado durante a madrugada, desde que a atividade não prejudique a sua frequência às aulas."}]'::jsonb,'C','oficial',44,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":44}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',45,'Direito do Consumidor','Mário, passando por dificuldades financeiras, solicitou, em juízo, a instauração de processo de repactuação de dívidas, que é deferido juntamente com a designação de audiência conciliatória. Na data fixada, a maior parte dos credores compareceu, com exceção do Banco XYZ S.A., que preferiu não se submeter à conciliação por superendividamento, por entender ser infrutífero o procedimento. A respeito da ausência do Banco XYZ S.A. à audiência, assinale a afirmativa correta.','[{"id":"A","text":"Acarreta o vencimento antecipado da dívida de Mário."},{"id":"B","text":"Interrompe os encargos da mora incidentes em seu crédito."},{"id":"C","text":"Permite-lhe ajuizar individualmente ação de cobrança do crédito."},{"id":"D","text":"Importa na submissão ao plano de repactuação de dívidas nas mesmas condições que os credores presentes."}]'::jsonb,'B','oficial',45,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":45}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',46,'Direito do Consumidor','Maria Victoria, em maio de 2023, decidiu aceitar a oferta do cartão de crédito Black, oferecido pelo Banco Y, do qual já era correntista há cerca de três anos. Contudo, em agosto de 2023, deixou de pagar a fatura de julho, no valor de R$ 5.300,00 (cinco mil e trezentos reais). Em razão disso, passado o vencimento, o Banco Y debitou automaticamente da conta-corrente dela o valor de R$ 300,00 (trezentos reais), referente ao denominado “pagamento mínimo” da fatura do cartão de crédito. Sobre a hipótese apresentada, assinale a afirmativa correta.','[{"id":"A","text":"Nas hipóteses em que não há previsão contratual para tanto, é possível ao banco debitar automaticamente o valor integral da fatura do cartão de crédito da conta-corrente do consumidor, quando ultrapassados 60 dias do inadimplemento e notificado o consumidor do débito após 30 dias da data do seu vencimento."},{"id":"B","text":"Independentemente de serem contratos distintos, pelo fato de existir uma única relação jurídica entre o consumidor e o banco, pode o banco debitar o valor mínimo da fatura do cartão de crédito automaticamente da conta-corrente do consumidor em caso de inadimplemento."},{"id":"C","text":"Havendo saldo em conta, mesmo não havendo previsão contratual para tanto, é possível ao banco debitar automaticamente o valor integral da fatura do cartão de crédito da conta-corrente do consumidor, quando ultrapassados 30 dias do inadimplemento e notificado o consumidor do débito."},{"id":"D","text":"Tratando-se de contratos distintos, de cartão de crédito e de conta-corrente, o banco somente pode fazer o débito na conta-corrente do valor mínimo da fatura se essa possibilidade estiver prevista de forma expressa, clara e destacada no contrato celebrado com a instituição financeira."}]'::jsonb,'D','oficial',46,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":46}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',47,'Direito Empresarial','Mercado Barra Velha Ltda. emitiu nota promissória no valor de R$ 19.800,00 (dezenove mil e oitocentos reais), com vencimento no dia 19 de dezembro de 2021. Não houve pagamento na data do vencimento e o credor somente levou o título a protesto no dia 2 de dezembro de 2023, sendo o protesto lavrado dois dias após. Sobre o caso, com base na legislação de regência da nota promissória e das condições para sua cobrança em face do emitente, assinale a afirmativa correta.','[{"id":"A","text":"O credor ainda poderá promover a execução da nota promissória em face do emitente em razão da interrupção da prescrição pelo protesto cambial."},{"id":"B","text":"O credor poderá promover a execução da nota promissória em face do emitente, considerando-se que ainda não expirou o prazo de cinco anos para a propositura da ação cambial."},{"id":"C","text":"O credor não pode promover a execução da nota promissória, em razão do protesto para a cobrança do emitente ser facultativo e do decurso do prazo de três anos da data do vencimento."},{"id":"D","text":"O título deveria ter sido apresentado até o primeiro dia útil após o vencimento, acarretando a perda do direito de ação em caso de inobservância dessa regra, embora o protesto seja facultativo para a cobrança."}]'::jsonb,'A','oficial',47,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":47}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',48,'Direito Empresarial','A padaria Jacaré dos Homens Ltda. teve sua falência requerida em razão da impontualidade no pagamento de duplicata de prestação de serviço, no valor de R$ 62.000,00 (sessenta e dois mil reais), aceita e devidamente protestada para este fim. A devedora procurou você, como advogado(a), informando que pretende depositar o valor cobrado. Acerca deste depósito, assinale a afirmativa correta.','[{"id":"A","text":"Deverá ser realizado em dinheiro, no prazo de quinze dias, contado da citação da devedora."},{"id":"B","text":"Compreenderá o valor total do crédito, acrescido de correção monetária, juros e honorários advocatícios."},{"id":"C","text":"Suspenderá o processo pelo prazo de trinta dias ou até que seja apreciado o mérito da cobrança, o que ocorrer por último."},{"id":"D","text":"Poderá ser realizado em dinheiro ou mediante prestação de caução real ou fidejussória no prazo de cinco dias, contado da citação."}]'::jsonb,'B','oficial',48,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":48}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',49,'Direito Empresarial','A sociedade empresária Pinheiros & Filhos Ltda., constituída em 2017 e com sede em Pancas, ES, pretende registrar como marca o sinal distintivo nominativo Pancadão, a ser utilizado nos produtos alimentícios que ela fornece a mercados, supermercados e armazéns na região de Pancas, ES, e Resplendor, MG. Na mesma cidade de Pancas, ES, há um estabelecimento explorado pelo empresário individual Domingos Guandu, cujo título é Bar e Mercearia Pancadão, constituído em 2000 e usado desde então, que revende os produtos alimentícios fornecidos por Pinheiros & Filhos Ltda. Considerados estes dados, a respeito do registro de marca, assinale a afirmativa correta.','[{"id":"A","text":"Não há impedimento do registro de Pancadão como marca, pois o uso do mesmo sinal distintivo para título de estabelecimento de terceiro, ainda que anterior, é incapaz de retirar a originalidade da marca."},{"id":"B","text":"Não há impedimento do registro de Pancadão como marca, haja vista que o sinal distintivo é novo e só há proteção para o título de estabelecimento no âmbito da propriedade industrial com o registro no INPI."},{"id":"C","text":"Pancadão não poderá ser registrado como marca por ser a reprodução de sinal distintivo característico de título de estabelecimento de terceiro, quando suscetível de causar confusão ou associação entre a marca e o título de estabelecimento."},{"id":"D","text":"Pancadão não poderá ser registrado como marca em razão da prioridade de uso do título de estabelecimento Pancadão pelo empresário Domingos Guandu, em âmbito nacional, decorrente da inscrição do empresário na Junta Comercial."}]'::jsonb,'C','oficial',49,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":49}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',50,'Direito Empresarial','Em relação aos elementos caracterizadores do empresário, assinale a afirmativa correta.','[{"id":"A","text":"O empresário caracteriza-se pelo exercício profissional de atos de comércio, dentre os quais não se inclui a prestação de serviços."},{"id":"B","text":"O exercício de profissão intelectual, de natureza artística, literária ou científica em nenhuma hipótese poderá servir para caracterizar o empresário."},{"id":"C","text":"O empresário caracteriza-se pelo exercício profissional de atividade econômica organizada para produção ou circulação de bens ou de serviços."},{"id":"D","text":"A inscrição do empresário na Junta Comercial e o exercício de atividade econômica em caráter habitual são os dois requisitos para sua caracterização."}]'::jsonb,'C','oficial',50,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":50}'::jsonb);

commit;
