-- Seed 46º EOU 2026 Tipo 1 - questões 51 a 60
begin;

insert into public.exam_questions (
  exam_id, question_number, area, prompt, options, correct_option,
  difficulty, sort_order, source_metadata
)
values (
  '46000000-2026-4000-8000-000000000001',
  51,
  'Direito Processual Civil',
  'Machado de Assis ajuizou ação indenizatória em face de Quincas Borba, pugnando pela condenação do réu ao pagamento de indenização por danos morais e materiais, resultantes do inadimplemento de contrato de prestação de serviços. O Juiz condenou o réu ao pagamento de indenização por danos morais no montante de R$ 5.000,00 (cinco mil reais) e danos materiais, a serem apurados em sede de liquidação de sentença, diante da necessidade de comprovação dos prejuízos que vêm sendo experimentados pelo autor, desde a ocorrência do ilícito. Quincas Borba contratou você, como advogado(a), para interpor recurso de apelação, buscando a reforma integral da sentença. Tomando o caso acima como premissa, assinale a opção que, corretamente, apresenta sua orientação.',
  '[{"id": "A", "text": "Enquanto não houver o julgamento do recurso de apelação, não será possível realizar a liquidação de sentença no capítulo referente aos danos materiais."}, {"id": "B", "text": "Apesar de Quincas Borba ter ofertado apelação, Machado de Assis poderá requerer desde logo a liquidação do capítulo dos danos materiais em autos apartados."}, {"id": "C", "text": "A liquidação de sentença somente poderá ser promovida por requerimento de Machado de Assis, pois o réu não detém legitimidade para requerer a liquidação de sentença."}, {"id": "D", "text": "Quincas Borba, em liquidação de sentença, poderá rediscutir a obrigação de pagamento dos danos materiais, sendo lícito ao Juiz modificar a sentença anteriormente proferida."}]'::jsonb,
  'B',
  'oficial',
  51,
  '{"source":"46º EOU 2026 - Tipo 1","questionNumber":51}'::jsonb
);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',52,'Direito Processual Civil','Por conta de danos sofridos em um acidente de trânsito, Juciara ajuizou ação em face de Carla, pleiteando a sua condenação ao pagamento de indenização. Julgado procedente o pedido, a Ré foi condenada ao pagamento de R$ 20.000,00 (vinte mil reais) a título de indenização por danos morais e materiais. Transitada em julgado a sentença, Carla imediatamente peticiona no referido processo, antes de qualquer depósito, oferecendo o pagamento de R$ 15.000,00 (quinze mil reais), com o devido depósito de tal quantia, e pleiteando o reconhecimento do cumprimento de sua obrigação. Sobre tal fato, assinale a afirmativa correta.','[{"id":"A","text":"Concluindo o Juiz pela insuficiência do depósito, incidirão a multa e os honorários advocatícios de 10% sobre o valor total devido."},{"id":"B","text":"Juciara deverá ser intimada do depósito e, caso impugne o valor, somente poderá levantar o montante total após o Juiz decidir sobre a suficiência do depósito."},{"id":"C","text":"Caso Juciara não se oponha ao valor ofertado, ainda que inferior à condenação, será reconhecida como satisfeita a obrigação, com a consequente extinção do processo."},{"id":"D","text":"O cumprimento de sentença depende da expressa manifestação de vontade da parte autora, de modo que Carla não poderia realizar o depósito dos valores devidos antes de intimada para tanto."}]'::jsonb,'C','oficial',52,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":52}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',53,'Direito Processual Civil','Paula ajuizou ação indenizatória por atraso de voo contra a companhia aérea Big Ben perante certo Juizado Especial Cível. Em sentença, o Magistrado condenou a companhia aérea ao pagamento de determinada quantia em dinheiro. Interposto recurso inominado pela companhia aérea, a Turma Recursal competente proveu o recurso. No entanto, em sua decisão, cometeu graves erros de aplicação de normas infraconstitucionais federais e normas constitucionais. A decisão colegiada, por outro lado, não incorreu em omissão, contradição, obscuridade ou erro material, e a matéria constitucional está devidamente pré-questionada. Diante desse cenário, assinale a afirmativa correta.','[{"id":"A","text":"Não há recurso cabível contra a decisão proferida pela Turma Recursal."},{"id":"B","text":"Paula deve opor embargos de declaração a fim de sanar os erros de interpretação de norma cometidos pela Turma Recursal."},{"id":"C","text":"Paula deve interpor recurso extraordinário contra a decisão da Turma Recursal, tendo em vista que a decisão incorreu em erros de aplicação de normas constitucionais."},{"id":"D","text":"Paula deve interpor recurso especial e recurso extraordinário simultaneamente, tendo em vista que o primeiro é cabível quando há violação à norma infraconstitucional federal, enquanto o segundo é cabível quando há violação à norma constitucional."}]'::jsonb,'C','oficial',53,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":53}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',54,'Direito Processual Civil','Aziz ajuizou ação de procedimento comum contra Betina, na qual requer sua condenação ao pagamento de R$ 10.000,00 (dez mil reais) por danos morais, após ter se sentido humilhado por Betina, que o xingou na frente de colegas de trabalho durante certa reunião profissional. Em primeiro grau, o Magistrado proferiu sentença que julgou parcialmente procedente o pedido de Aziz, condenando Betina ao pagamento de R$ 6.000,00 (seis mil reais). Aberto o prazo de 15 dias úteis para a interposição de recurso contra a sentença, apenas Aziz interpôs apelação, tendo requerido a reforma da decisão para que Betina fosse condenada a pagar o valor integral de R$ 10.000,00 (dez mil reais). Após a interposição do recurso de apelação por Aziz, o Magistrado abriu o prazo para que Betina apresentasse contrarrazões no prazo legal. Diante desse cenário, assinale a afirmativa correta.','[{"id":"A","text":"Betina poderá apresentar contrarrazões ao recurso unicamente no prazo de 15 dias corridos."},{"id":"B","text":"Betina poderá apresentar contrarrazões ao recurso no prazo de 15 dias úteis e, nos 15 dias úteis subsequentes, poderá interpor apelação adesiva."},{"id":"C","text":"Betina poderá apresentar, no prazo concedido, contrarrazões ao recurso e interpor apelação adesiva; caso o recurso de apelação de Aziz seja inadmitido, o recurso de Betina também o será."},{"id":"D","text":"Betina poderá apresentar apenas contrarrazões ao recurso, não sendo possível a interposição de recurso adesivo no caso concreto, tendo em vista que o recurso adesivo não é admissível em apelação."}]'::jsonb,'C','oficial',54,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":54}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',55,'Direito Processual Civil','João propõe ação de exigência das contas contra o seu sócio, Vinícius, para verificar a regularidade da administração dos bens da pessoa jurídica Discos de Vinil Ltda, da qual ambos são sócios. Vinícius contesta o pedido, sustentando que já havia prestado as contas extrajudicialmente, bem como efetuado a juntada da prestação de contas em conjunto com a contestação. Nesse caso, continuando o procedimento, o Juiz deverá','[{"id":"A","text":"intimar João para se manifestar no prazo de 15 dias."},{"id":"B","text":"julgar antecipadamente o mérito, impondo a Vinícius o dever de prestar as contas."},{"id":"C","text":"extinguir o processo sem resolução do mérito, ante a falta de interesse de agir de João."},{"id":"D","text":"designar, necessariamente, uma audiência de instrução e julgamento para colher o depoimento pessoal das partes, a fim de deslindar a controvérsia."}]'::jsonb,'A','oficial',55,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":55}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',56,'Direito Processual Civil','A Associação de Defesa dos Usuários de Smartphone (ADUS) ajuizou ação civil pública em face do fabricante X, requerendo a sua condenação para a retirada do aparelho Y do mercado, em razão de vícios em seu processo construtivo. Após a oferta de contestação pelo réu, no curso da fase instrutória, houve abandono imotivado da causa pela Associação. Sobre o caso narrado, assinale a afirmativa correta.','[{"id":"A","text":"É vedado ao Poder Público se habilitar como litisconsorte na causa."},{"id":"B","text":"O Ministério Público poderá assumir a titularidade da ação, assim como outra associação legitimada."},{"id":"C","text":"A ação deverá ser extinta sem resolução do mérito, fundado em abandono da causa, independentemente de requerimento do réu."},{"id":"D","text":"A associação, para propor a ação civil pública, deve necessariamente ter sido constituída há pelo menos um ano, vedada a dispensa de tal requisito por decisão judicial."}]'::jsonb,'B','oficial',56,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":56}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',57,'Direito Penal','Daniel chegou em casa embriagado e exigiu que sua esposa, Bianca, praticasse com ele conjunção carnal. Diante da recusa de Bianca, Daniel passou a empregar a coação física contra a sua esposa, porém, os gritos de Bianca foram ouvidos por vizinhos, que lograram entrar no imóvel e imobilizar Daniel, antes que consumasse o ato. Daniel foi denunciado pelo delito de estupro, mas, alguns meses após os fatos, e antes do recebimento da denúncia, Daniel e Bianca reataram o casamento. A você, na qualidade de advogado(a) de defesa de Daniel, cabe alegar','[{"id":"A","text":"a retratação tácita da representação da ofendida."},{"id":"B","text":"a causa de diminuição de pena em razão da tentativa."},{"id":"C","text":"a excludente de ilicitude ante o exercício regular de um direito."},{"id":"D","text":"o perdão tácito em razão da manutenção da sociedade conjugal."}]'::jsonb,'B','oficial',57,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":57}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',58,'Direito Penal','Hermenegildo e Ataulfo são amigos desde a infância, mas, devido a divergências políticas, tornaram-se inimigos. Na véspera da eleição para Presidente do Sindicato da classe a qual pertencem, eles se encontraram em um botequim da cidade de Sucupira e o primeiro sacou sua pistola, que estava carregada com 17 munições, e disparou uma vez, com a intenção de matar, na direção de Ataulfo, atingindo-o no joelho. No clima tenso que surgiu depois do ato, Ataulfo lembrou a Hermegildo que ambos formaram o ataque do time de futebol que se sagrou campeão juvenil na escola primária. Hermenegildo, emocionado com a lembrança do ex-amigo, abandonou a arma de fogo no chão e foi embora. Ataulfo sobreviveu sem sequelas. Diante da situação hipotética narrada, assinale a afirmativa correta.','[{"id":"A","text":"Houve arrependimento voluntário, e Hermenegildo deve responder pelo crime que desejou consumar."},{"id":"B","text":"Houve crime impossível, pois a conduta de Hermenegildo mostrou-se absolutamente ineficaz."},{"id":"C","text":"Houve tentativa imperfeita, pois a hesitação de Hermenegildo impediu o resultado mais gravoso."},{"id":"D","text":"Houve desistência voluntária, e Hermenegildo deve responder pelos atos já praticados."}]'::jsonb,'D','oficial',58,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":58}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',59,'Direito Penal','Leandro e Leonardo planejaram matar Sérgio e, para tanto, resolveram simular um assalto durante o qual aqueles efetuariam disparos com armas de fogo na direção deste. Leandro e Leonardo foram conduzidos ao local em dois carros pilotados, respectivamente, por José e Luciano, que estavam cientes do plano, mas se recusaram a pegar nas armas de fogo. Sérgio faleceu em razão dos ferimentos. Diante da situação hipotética, assinale a opção correta.','[{"id":"A","text":"José e Luciano são partícipes do crime de homicídio doloso consumado praticado por Leandro e Leonardo."},{"id":"B","text":"José e Luciano praticaram tentativa de roubo, enquanto Leandro e Leonardo praticaram o crime de homicídio."},{"id":"C","text":"José e Luciano são autores colaterais do crime de roubo, enquanto Leandro e Leonardo são autores mediatos do crime de homicídio."},{"id":"D","text":"José e Luciano não integram o concurso de agentes, pois somente Leandro e Leonardo detinham o domínio final da empreitada criminosa."}]'::jsonb,'A','oficial',59,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":59}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',60,'Direito Penal','Paulo, ao sair irritado da partida em que o seu clube de futebol havia perdido de goleada para o maior rival, sacou sua arma de fogo e, mesmo não desejando diretamente matar alguém, mas assumindo o risco de fazê-lo, disparou diversas vezes na direção de uma estação de trem, pois tinha ciência de que ela estava lotada e servia como ponto de encontro para a torcida do clube rival. Um dos disparos acabou atingindo fatalmente um padre, que se deslocava em direção à igreja para oficiar a missa. Sobre o crime praticado por Paulo, assinale a afirmativa correta.','[{"id":"A","text":"Homicídio, mediante dolo eventual."},{"id":"B","text":"Homicídio culposo, pois sua intenção não era causar a morte."},{"id":"C","text":"Tentativa de homicídio, pois sua intenção não era causar a morte."},{"id":"D","text":"Homicídio mediante preterdolo, pois o padre não estava entre os alvos de Paulo."}]'::jsonb,'A','oficial',60,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":60}'::jsonb);

commit;
