-- Seed 46º EOU 2026 Tipo 1 - questões 61 a 70
begin;

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',61,'Direito Penal','Josué foi condenado, por sentença transitada em julgado, pela prática do crime de tráfico de drogas, a cumprir a pena de 9 anos de reclusão e 900 dias-multa. Durante a execução da pena, entre as opções de trabalho e estudo que lhe foram ofertadas, Josué optou por aderir aos cursos profissionalizantes a distância, com o objetivo de reduzir o tempo de encarceramento. Diante de tal situação hipotética, assinale a afirmativa correta.','[{"id":"A","text":"Josué tem direito à remição na razão de um dia de pena para cada dia de estudo."},{"id":"B","text":"O tempo de ensino a distância pode ser computado para fins de remição da pena."},{"id":"C","text":"Em caso de falta grave, o Juiz poderá revogar a integralidade do tempo remido do ato praticado."},{"id":"D","text":"A detração por trabalho na prisão é mais vantajosa do que a remição do tempo de pena pelo estudo."}]'::jsonb,'B','oficial',61,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":61}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',62,'Direito Processual Penal','Pedro costumava consumir maconha. Vislumbrando a perspectiva de lucro, passou a plantá-la e a fabricar artesanalmente cigarros de maconha, mantendo-os parcialmente em depósito e vendendo o restante da produção por meio de aplicativo de mensagens telefônicas. Devido ao aumento da divulgação do serviço prestado, Pedro foi investigado e preso quando possuía, em casa, 500 gramas de maconha, sendo acusado da prática do crime de tráfico de drogas por cinco vezes, haja vista que importou sementes, plantou-as, fabricou cigarros e os manteve em depósito, além de vender parte da produção. Você, como advogado(a), foi constituído(a) por Pedro para atuar no curso da Ação Penal. Sobre o caso narrado, assinale a opção que indica, corretamente, a orientação jurídica que você prestou.','[{"id":"A","text":"Pedro praticou apenas o crime de porte de drogas para o consumo pessoal, pois a droga foi produzida e apreendida no interior de sua casa."},{"id":"B","text":"Pedro praticou o crime de tráfico de drogas por cinco vezes, sob continuidade delitiva, razão pela qual faz jus à mitigação da pena total."},{"id":"C","text":"Pedro praticou crime único de tráfico de drogas, pois o tipo penal aplicável ao caso é misto, o que atrai a incidência do princípio da alternatividade."},{"id":"D","text":"Pedro praticou o crime de tráfico de drogas por cinco vezes, sob concurso formal, razão pela qual faz jus à mitigação da pena total."}]'::jsonb,'C','oficial',62,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":62}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',63,'Direito Processual Penal','Marivaldo foi denunciado por organização criminosa e peculato. A denúncia foi lastreada, exclusivamente, no depoimento de Sérgio, corréu, que celebrou acordo de colaboração premiada com o Ministério Público. Assim, recebida a denúncia, foram citados ambos os réus, sendo que a citação de Marivaldo ocorreu no dia 10/05, e a de Sérgio, no dia 20/05 do corrente ano. De acordo com o caso narrado, na qualidade de advogado(a) de Marivaldo, assinale a opção que apresenta a conduta adequada a ser adotada.','[{"id":"A","text":"O prazo de apresentação da resposta à acusação é de dez dias a contar da citação do último corréu, tratando-se de prazo comum às partes."},{"id":"B","text":"O prazo de apresentação da resposta à acusação é de dez dias a contar da citação de Marivaldo, podendo ser encerrado antes do prazo de Sérgio."},{"id":"C","text":"Deve ser alegada a violação ao contraditório, pois o corréu delatado deve participar das tratativas de celebração do acordo de colaboração premiada."},{"id":"D","text":"Deve ser alegada a ausência de justa causa para o recebimento da denúncia, pois a palavra do colaborador, sem provas de corroboração, é insuficiente para o recebimento da denúncia."}]'::jsonb,'D','oficial',63,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":63}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',64,'Direito Processual Penal','Vanessa foi denunciada pelo crime de furto por ter subtraído um celular. Na audiência, a prova testemunhal apontou que Vanessa utilizou de grave ameaça, consistente em apontar um revólver para a vítima, como meio de obtenção do celular. A vítima não compareceu à audiência de reconhecimento de pessoas. O Juiz, usando a prova testemunhal, sem qualquer aditamento da denúncia por parte do Ministério Público, condenou Vanessa pelo crime de roubo. Sobre a hipótese, assinale a opção que apresenta, corretamente, o que a defesa deve alegar na apelação.','[{"id":"A","text":"A violação ao princípio do ne bis in idem."},{"id":"B","text":"A violação ao princípio da correlação entre acusação e sentença."},{"id":"C","text":"A impossibilidade de a prova testemunhal servir para condenar a ré, inclusive pelo furto."},{"id":"D","text":"A nulidade do processo, porque a condenação dependeria necessariamente do reconhecimento pessoal feito pela vítima."}]'::jsonb,'B','oficial',64,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":64}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',65,'Direito Processual Penal','Anderson está sendo investigado pela prática do crime de extorsão mediante sequestro. Depois da quebra dos sigilos bancários e fiscal, a polícia efetuou o indiciamento de Anderson, sendo certo que não existia mais nenhuma diligência pendente. A defesa de Anderson requereu o acesso aos autos da investigação, que foi negado pelo Delegado de Polícia, com o argumento da inquisitividade e sigilo do inquérito policial. O Juiz também negou o acesso afirmando que o inquérito é sigiloso e possuía extratos bancários e fiscais. Assinale a opção que indica, corretamente, o argumento que você, na condição de advogado(a), deve usar no recurso para garantir o acesso ao inquérito.','[{"id":"A","text":"O princípio de in dubio pro reo."},{"id":"B","text":"O direito absoluto de acessar o inquérito, em qualquer hipótese, como consectário da ampla defesa."},{"id":"C","text":"O princípio da publicidade, que deve ser aplicado tanto na fase de investigação quanto na fase processual."},{"id":"D","text":"É direito do advogado regularmente constituído ter acesso às diligências já documentadas, somado ao fato de não existir nenhuma diligência pendente."}]'::jsonb,'D','oficial',65,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":65}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',66,'Direito Processual Penal','Nicola injuriou Robson e Carlos, servidores públicos federais, por fatos relacionados a times de futebol, mas sem caráter racial na injúria. Robson ofereceu queixa-crime, ao passo que Carlos deixou passar o prazo de decadência. O Juiz extinguiu a punibilidade, sob o argumento de que a decadência do direito de um dos envolvidos provocava a extinção de punibilidade em relação a todos. Assinale a opção que apresenta o recurso que você, na condição de advogado(a) de Robson, deve apresentar.','[{"id":"A","text":"O princípio da eventualidade demonstra o equívoco da decisão do Juiz."},{"id":"B","text":"O direito de queixa é autônomo para cada vítima, o que torna impossível, juridicamente, a extensão da decadência nesse caso."},{"id":"C","text":"A decadência não extingue a punibilidade, sendo apenas uma causa de diminuição a ser levada em consideração na dosimetria da pena."},{"id":"D","text":"A propositura de queixa por parte de Robson interrompeu o prazo de decadência para Carlos, uma vez que não há que se falar em extinção de punibilidade."}]'::jsonb,'B','oficial',66,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":66}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',67,'Direito Processual Penal','Leandro oferece queixa-crime no Juizado Especial Criminal. O Juiz rejeita a queixa sustentando a existência de decadência. Na condição de advogado(a) de Leandro, assinale a opção que indica, corretamente, o recurso que deve ser interposto contra a decisão que rejeitou a queixa.','[{"id":"A","text":"Apelação."},{"id":"B","text":"Recurso inominado."},{"id":"C","text":"Carta testemunhável."},{"id":"D","text":"Recurso em sentido estrito."}]'::jsonb,'A','oficial',67,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":67}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',68,'Direito Processual Penal','Débora, primária e sem antecedentes, foi presa em flagrante no Aeroporto Internacional de Guarulhos, quando desembarcava no Brasil, em voo vindo do exterior, com um artefato que simulava uma arma de fogo de uso proibido na bagagem, ou seja, um simulacro que pode facilmente ser confundido com uma arma de fogo real. O simulacro é produto de importação proibida no Brasil. Débora foi enquadrada no delito de tráfico internacional de armas, previsto no Art. 18 do Estatuto do Desarmamento, cuja pena cominada é de 8 a 16 anos de reclusão, com a causa de aumento de metade (Art. 19 do Estatuto). A Polícia Federal lavrou o auto de prisão em flagrante e Débora foi submetida à audiência de custódia perante o Juiz Federal de Guarulhos. Como advogado(a) de Débora, assinale a afirmativa que contém as teses defensivas corretas.','[{"id":"A","text":"A atipicidade do fato, ante o crime impossível e, ainda que assim não fosse, há incompetência absoluta da Justiça Federal."},{"id":"B","text":"A desclassificação para contrabando (pena de 2 a 5 anos) e o cabimento de liberdade provisória, com ou sem medidas cautelares diversas da prisão."},{"id":"C","text":"Como Débora é mulher e não tem antecedentes criminais, e o fato não foi cometido mediante violência ou grave ameaça, é cabível a substituição da prisão preventiva por domiciliar."},{"id":"D","text":"O fato foi meramente tentado, de forma que a pena mínima cominada com a redução máxima pela tentativa é igual a 4 anos, tornando cabível o acordo de não persecução penal."}]'::jsonb,'B','oficial',68,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":68}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',69,'Direito Previdenciário','Antônio José, segurado obrigatório do Regime Geral de Previdência Social, completou 65 anos de idade, após 30 anos ininterruptos de atividade remunerada como segurado empregado. Diante disso, procurou você, como advogado(a), para ser orientado sobre sua aposentadoria. Assinale a opção que apresenta, corretamente, a sua orientação.','[{"id":"A","text":"Antônio não possui carência para fins de aposentadoria."},{"id":"B","text":"Antônio já possui idade e carência para fins de aposentadoria."},{"id":"C","text":"Antônio somente poderia, no caso narrado, se aposentar após 35 anos de contribuição."},{"id":"D","text":"Antônio não possui idade mínima, na forma fixada pela Constituição da República de 1988."}]'::jsonb,'B','oficial',69,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":69}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',70,'Direito Previdenciário','Manuela Dias, empregada doméstica, procurou você, como advogado(a), para receber orientação jurídica para uma demanda relacionada a acidente de trabalho, que ocorreu durante os seus afazeres diários na residência da empregadora doméstica, que gerou incapacidade temporária. Assinale a opção que indica a orientação correta.','[{"id":"A","text":"Manuela poderá usufruir de benefício previdenciário por incapacidade temporária, ainda que possua menos de 12 contribuições mensais."},{"id":"B","text":"O acidente de trabalho somente será reconhecido como tal caso haja incapacidade mínima de seis meses para o trabalho, avaliada por perícia médica."},{"id":"C","text":"A conexão da incapacidade com o trabalho poderá ser aferida pelo INSS, mas nunca com a aplicação do Nexo Técnico Epidemiológico Previdenciário – NTEP."},{"id":"D","text":"A incapacidade de Manuela, na situação narrada, nunca poderia ser decorrente de doenças, pois o acidente de trabalho é sempre súbito, imediato e instantâneo."}]'::jsonb,'A','oficial',70,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":70}'::jsonb);

commit;
