-- Seed 46º EOU 2026 Tipo 1 - questões 21 a 30
begin;

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',21,'Direito Internacional','Um cidadão brasileiro, domiciliado na Espanha, faleceu deixando um testamento particular que dispõe sobre bens situados tanto no exterior quanto no Brasil. Após a sua morte, os herdeiros promoveram, de comum acordo, perante autoridade notarial estrangeira competente, procedimento consensual de confirmação do testamento particular e partilha do patrimônio, incluindo os bens localizados no Brasil. Posteriormente, requereram ao Superior Tribunal de Justiça (STJ) a homologação do ato notarial estrangeiro, alegando a inexistência de litígio entre os herdeiros e a plena validade do procedimento conforme a legislação do país de origem. Sobre o caso apresentado, à luz do sistema jurídico brasileiro, assinale a afirmativa correta.','[{"id":"A","text":"A homologação será possível apenas se o ato estrangeiro for convertido em decisão judicial no país de origem, pois somente decisões judiciais estrangeiras são passíveis de homologação pelo STJ."},{"id":"B","text":"O ato notarial poderá ser homologado pelo STJ desde que todos os herdeiros sejam capazes e tenham manifestado consentimento expresso quanto à confirmação do testamento e à partilha dos bens, inclusive os situados no Brasil."},{"id":"C","text":"A homologação deverá ser deferida parcialmente, produzindo efeitos automáticos sobre os bens situados no Brasil, em respeito ao princípio da autonomia da vontade dos herdeiros e ao reconhecimento internacional dos atos notariais."},{"id":"D","text":"O ato notarial estrangeiro não poderá ser homologado na parte relativa aos bens situados no Brasil, pois a confirmação de testamento particular e a partilha desses bens se inserem na competência jurisdicional exclusiva da autoridade judiciária brasileira."}]'::jsonb,'D','oficial',21,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":21}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',22,'Direito Internacional','François, cidadão francês, residente e domiciliado na Holanda, e Maria, cidadã brasileira, residente e domiciliada na França, são casados. Conheceram-se na Alemanha, onde concluíram o doutorado em Direito Internacional na Universidade de Frankfurt. Os nubentes eram domiciliados na Alemanha na ocasião do casamento e tiveram em Frankfurt o seu primeiro domicílio conjugal. Posteriormente, mudaram-se para países diferentes por razões profissionais. Após alguns meses, resolveram não dar continuidade ao casamento. Maria pretende ajuizar ação de divórcio no Brasil porque está prestes a retornar ao seu país de origem. Sobre a hipótese, assinale a opção que indica a lei que será aplicada ao regime de bens de acordo com a legislação brasileira, em especial a Lei de Introdução às Normas do Direito Brasileiro.','[{"id":"A","text":"Francesa."},{"id":"B","text":"Brasileira."},{"id":"C","text":"Alemã."},{"id":"D","text":"Holandesa."}]'::jsonb,'C','oficial',22,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":22}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',23,'Direito Financeiro','O Município Alfa estava enfrentando dificuldades para pagar em dia a remuneração de seus servidores públicos municipais. Em razão disso, resolveu requerer à instituição financeira federal BNDES um empréstimo, a fim de pagar as remunerações em atraso. O Município ofereceu, em garantia do empréstimo, terrenos de sua propriedade, cujo valor de mercado inclusive suplantava o montante a ser emprestado. Diante desse cenário, assinale a afirmativa correta.','[{"id":"A","text":"É proibido ao BNDES realizar empréstimo para o pagamento de despesas com pessoal."},{"id":"B","text":"Como houve oferta de garantia em valor superior ao do empréstimo, este deverá ser realizado pelo BNDES."},{"id":"C","text":"É facultado ao BNDES realizar o empréstimo, mas apenas se reputar que as garantias oferecidas são de liquidez satisfatória."},{"id":"D","text":"Somente uma instituição financeira controlada pelo Estado em que se localiza o Município Alfa poderia realizar tal empréstimo."}]'::jsonb,'A','oficial',23,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":23}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',24,'Direito Financeiro','Em determinado ano, na elaboração do projeto de Lei Orçamentária Anual (LOA) da União, o Poder Executivo resolveu inserir as previsões de despesas para os exercícios seguintes, com a especificação dos investimentos plurianuais e daqueles em andamento. Sobre esse projeto de LOA, à luz das regras constitucionais de elaboração das leis orçamentárias, assinale a afirmativa correta.','[{"id":"A","text":"Veiculou indevidamente investimentos plurianuais e aqueles em andamento, os quais somente poderiam constar do Plano Plurianual (PPA)."},{"id":"B","text":"Inseriu, equivocadamente, os investimentos plurianuais em seu conteúdo, pois deveriam estar previstos na Lei de Diretrizes Orçamentárias (LDO)."},{"id":"C","text":"Adequa-se às disposições constitucionais que permitem tais inserções dos investimentos plurianuais e daqueles em andamento."},{"id":"D","text":"Poderia conter, apenas, os investimentos já em andamento, uma vez que os investimentos plurianuais somente poderiam constar do Plano Plurianual (PPA)."}]'::jsonb,'C','oficial',24,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":24}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',25,'Direito Tributário','Com necessidade de ampliar os gastos na área da seguridade social, a União criou uma nova contribuição de seguridade social, por meio da Lei Ordinária nº XXX/2024, publicada em 1º de setembro de 2024, cuja cobrança se iniciou em 1º de novembro de 2024. Diante desse cenário, assinale a afirmativa correta.','[{"id":"A","text":"A Lei Ordinária nº XXX/2024 é inconstitucional por violar tanto a reserva de lei complementar como os princípios da anterioridade tributária anual e nonagesimal."},{"id":"B","text":"Embora não viole o princípio da anterioridade tributária anual, a Lei Ordinária nº XXX/2024 é inconstitucional por violar tanto a reserva de lei complementar como o princípio da anterioridade tributária nonagesimal."},{"id":"C","text":"Não há qualquer inconstitucionalidade na Lei Ordinária nº XXX/2024, uma vez que as novas contribuições de seguridade social são instituídas por meio de lei ordinária e constituem exceção aos princípios da anterioridade tributária anual e nonagesimal."},{"id":"D","text":"As novas contribuições de seguridade social constituem exceção aos princípios da anterioridade tributária anual e nonagesimal, de modo que a única inconstitucionalidade formal presente na Lei Ordinária nº XXX/2024 é a de violar a reserva de lei complementar."}]'::jsonb,'B','oficial',25,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":25}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',26,'Direito Tributário','Mateus devia um valor elevado ao Fisco Federal, em dívidas de certo tributo federal devidamente lançadas e inscritas em Dívida Ativa da União ainda não prescritas, o que levou a Procuradoria da Fazenda Nacional (PFN), em fevereiro de 2020, a ajuizar execução fiscal contra ele. Mateus não foi localizado para ser citado nem foram encontrados bens sobre os quais poderia recair a penhora, tendo sido a PFN cientificada desses fatos, em abril de 2020. Assim, foi requerida e realizada a citação de Mateus por edital, ainda em abril de 2020. Em julho de 2025, sem que a situação se alterasse, o Magistrado, ouvida previamente a Fazenda Nacional, decretou a ocorrência da prescrição de tais créditos tributários. Diante desse cenário, assinale a afirmativa correta.','[{"id":"A","text":"Ocorreu a prescrição direta de tais créditos, pois foi alcançado o prazo prescricional quinquenal previsto no Código Tributário Nacional."},{"id":"B","text":"A ausência de citação pessoal de Mateus impede o curso da prescrição, de modo que esta, nesse caso, não poderia ter se consumado."},{"id":"C","text":"A prescrição intercorrente prevista no Código Tributário Nacional, ocorrida na pendência do processo de execução fiscal, fulminou tais créditos tributários."},{"id":"D","text":"A prescrição intercorrente prevista na Lei de Execuções Fiscais ainda não havia sido atingida, pois não se computou na contagem geral do prazo o período de 1 ano de suspensão do curso da execução."}]'::jsonb,'D','oficial',26,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":26}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',27,'Direito Tributário','João da Silva recebeu vultosa importância da sociedade empresária em que trabalhava, a título de indenização por danos morais, por ter sido exposto meses antes, em público, diante de seus colegas, a uma situação vexatória. No momento do pagamento do valor da indenização, a sociedade empresária reteve na fonte o Imposto sobre a Renda que entendeu devido, recolhendo-o em DARF no mesmo ato. João, inconformado com a retenção, impugnou administrativamente a cobrança, mas a decisão de primeira instância administrativa denegou a restituição do imposto. João então consultou você, como advogado(a), pretendendo reaver o imposto que entende ser indevido. Diante desse cenário, assinale a afirmativa correta.','[{"id":"A","text":"Foi correta a retenção do Imposto de Renda sobre aquela verba indenizatória, por se tratar de fato ocorrido em relação de emprego, equiparando-a a verba salarial."},{"id":"B","text":"Caso queira promover ação anulatória contra a decisão administrativa que denegou a restituição do Imposto sobre a Renda, João terá um prazo máximo de dois anos para fazê-lo."},{"id":"C","text":"João somente poderá requerer judicialmente a restituição do valor de Imposto sobre a Renda retido indevidamente, por ter natureza indenizatória, após esgotar a via administrativa tributária em todas as instâncias."},{"id":"D","text":"Tendo sido negado em primeira instância administrativa o seu pedido de restituição do Imposto sobre a Renda que entende indevidamente retido, João somente poderá recorrer à segunda instância administrativa após realizar depósito prévio."}]'::jsonb,'B','oficial',27,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":27}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',28,'Direito Tributário','A lei federal que instituiu a Contribuição de Intervenção no Domínio Econômico incidente sobre a importação e a comercialização de petróleo e seus derivados (Cide Combustíveis) fixou a alíquota do álcool etílico combustível em R$ 37,20/m³ para a comercialização no mercado interno. Contudo, o governo federal, querendo estimular o uso do álcool etílico combustível, pelo Decreto do Presidente da República nº XXX, de 1º de agosto de 2024, reduziu esta alíquota para R$ 20,50/m³. Mudada a política governamental sobre a matéria, pelo Decreto nº YYY, datado de 1º de fevereiro de 2025, tal alíquota foi restabelecida em R$ 37,20/m³, com efeitos a serem produzidos a partir de 3 de junho de 2025. Diante desse cenário, assinale a afirmativa correta.','[{"id":"A","text":"A produção de efeitos do Decreto nº YYY a partir de 3 de junho de 2025 viola o princípio da anterioridade tributária anual."},{"id":"B","text":"A redução da alíquota para R$ 20,50/m³ por decreto é inconstitucional, ainda que seja mais benéfica ao sujeito passivo tributário."},{"id":"C","text":"A redução da alíquota para R$ 20,50/m³ e seu restabelecimento para R$ 37,20/m³ podem ser feitas por decreto."},{"id":"D","text":"O restabelecimento de tal alíquota da Cide Combustíveis para o patamar de R$ 37,20/m³ por decreto viola o princípio da legalidade tributária."}]'::jsonb,'C','oficial',28,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":28}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',29,'Direito Tributário','O Município Alfa, por lei ordinária municipal, criou a Taxa de Fiscalização de Cemitérios, relativa ao custeio das atividades de fiscalização das instalações e atividades das concessionárias de cemitérios em território municipal, tendo tais concessionárias como contribuintes. A lei criadora estabeleceu que a data de pagamento dessa taxa seria fixada em decreto do Prefeito Municipal. O Decreto Municipal XX/2023 fixou a data de pagamento em 15 dias após o recebimento da notificação para pagamento. Diante desse cenário, assinale a afirmativa correta.','[{"id":"A","text":"Somente lei municipal, e não mero decreto, poderia fixar o prazo de pagamento da referida taxa."},{"id":"B","text":"O Decreto Municipal XX/2023 não poderia fixar a data de pagamento dessa taxa em 15 dias, por contrariar o prazo de 30 dias previsto no Código Tributário Nacional (CTN)."},{"id":"C","text":"Como a fiscalização de cemitérios configura uma taxa de polícia, e não uma taxa de serviço público específico e divisível, tal taxa não poderia ser instituída pelo Município Alfa."},{"id":"D","text":"Ainda que não houvesse previsão na lei instituidora do tributo de que seria um decreto a fixar a data de pagamento dessa taxa, o Decreto Municipal XX/2023 seria ato normativo apto a fazê-lo."}]'::jsonb,'D','oficial',29,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":29}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',30,'Direito Administrativo','A sociedade empresária Begônia deseja participar de um procedimento licitatório, na modalidade concorrência, para a contratação de uma obra, que adotará a sequência adotada como regra na Lei nº 14.133/2021, mas está com receio de ser prejudicada no julgamento das propostas, que antecede à fase de habilitação. Em razão disso, a sociedade empresária consultou você, como advogado(a), a fim de esclarecer a possibilidade de apresentar um recurso administrativo, o momento correto para fazê-lo e os efeitos dele decorrentes, caso tal receio venha a ser concretizado. Sobre essa situação hipotética, assinale a opção que indica, corretamente, o esclarecimento que você prestou.','[{"id":"A","text":"Não há a possibilidade de se apresentar um recurso administrativo contra o julgamento das propostas, diante da vedação expressa na aludida norma."},{"id":"B","text":"Apenas depois da habilitação é que caberá a apresentação de um recurso administrativo contra o julgamento das propostas, de modo que é necessário aguardar o prosseguimento do certame para a manifestação da intenção de recorrer no momento oportuno."},{"id":"C","text":"O pedido de reconsideração em relação ao julgamento das propostas deve ser prontamente apresentado ao fim da respectiva fase e possui efeito suspensivo, de modo que a licitação só seguirá para a fase de habilitação após a apreciação das irresignações apresentadas."},{"id":"D","text":"A intenção de recorrer do julgamento das propostas deve ser imediatamente manifestada, mas o prazo para a apresentação das razões recursais será iniciado na data da intimação ou da lavratura da ata de habilitação ou inabilitação, pois sua apreciação dar-se-á em fase única."}]'::jsonb,'D','oficial',30,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":30}'::jsonb);

commit;
