-- Seed 46º EOU 2026 Tipo 1 - questões 31 a 40
begin;

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',31,'Direito Administrativo','O Estado Alfa, cuja capital é o Município Beta, mediante decreto do Governador, em observância às formalidades legais, declarou de utilidade pública uma grande área localizada no Município Sigma, sede de Comarca, a qual abarca o imóvel pertencente ao particular João. Em razão do grande apego emocional com a localidade, onde vive há 25 anos, João recusou todas as propostas oferecidas pelo Poder Público e tentou impedir que as autoridades administrativas estaduais ingressassem no terreno do seu imóvel para a realização de levantamentos. Por isso, o Estado Alfa pretende ingressar, em juízo, com uma ação visando à desapropriação do bem. Preocupado, João contratou você, como advogado(a), para defendê-lo na futura demanda judicial. Nesse cenário, considerando as disposições do Decreto-Lei nº 3.365/1941, que versa sobre as desapropriações por utilidade pública, assinale a afirmativa correta.','[{"id":"A","text":"A ação judicial deverá ser proposta pelo expropriante no foro da situação do bem imóvel, ou seja, na Comarca do Município Sigma."},{"id":"B","text":"As autoridades administrativas do Estado Alfa poderão ingressar nas áreas compreendidas pela declaração de utilidade pública após a autorização judicial específica, ouvido o expropriado João."},{"id":"C","text":"O Estado Alfa poderá se imitir provisoriamente na posse do imóvel de João, desde que, declarada a situação de urgência, deposite, em juízo, o valor que o expropriado João entender justo a título de indenização."},{"id":"D","text":"Incumbirá ao expropriado João, em sede de contestação, expor todas as razões de fato e de direito com que impugna o pedido do expropriante, especificando as provas que pretende produzir para demonstrar que inexiste utilidade pública na desapropriação almejada pelo Estado Alfa."}]'::jsonb,'A','oficial',31,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":31}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',32,'Direito Administrativo','A sociedade empresária Alfa tomou conhecimento de que o Conselho Diretor da Agência Reguladora Beta realizou reunião deliberativa, na semana anterior, tendo por objeto discussões sobre documentos classificados como sigilosos, bem como sobre matérias de natureza administrativa. Considerando que a data da referida reunião não foi previamente divulgada no sítio da agência reguladora na internet, tampouco foi gravada em meio eletrônico, os sócios da entidade privada procuraram você para, na qualidade de advogado (a), prestar a devida consultoria jurídica. Nesse cenário, à luz da Lei no 13.848/2019, que dispõe sobre a gestão, a organização, o processo decisório e o controle social das agências reguladoras, assinale a opção que apresenta, corretamente, a orientação jurídica prestada.','[{"id":"A","text":"A reunião deliberativa do Conselho Diretor da Agência Reguladora Beta deverá ser anulada, na medida em que não houve a sua gravação em meio eletrônico."},{"id":"B","text":"Inexiste irregularidade na reunião deliberativa do Conselho Diretor da Agência Reguladora Beta, já que foram discutidos documentos classificados como sigilosos, bem como matérias de natureza administrativa."},{"id":"C","text":"Muito embora a gravação, em meio eletrônico, da reunião deliberativa do Conselho Diretor da Agência Reguladora Beta não fosse obrigatória, era necessário a prévia divulgação da sua data no sítio da referida autarquia na internet."},{"id":"D","text":"Para que a reunião deliberativa do Conselho Diretor da Agência Reguladora Beta seja anulada, a sociedade empresária Alfa deverá demonstrar prejuízo em razão da ausência de divulgação prévia desta no sítio da referida autarquia na internet."}]'::jsonb,'B','oficial',32,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":32}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',33,'Direito Administrativo','O Ministério Público ingressou, em Juízo, com ação de improbidade administrativa em face de João, agente público no Município Alfa, sob o fundamento de que ele teria, em outubro de 2025, frustrado, em ofensa à imparcialidade, o caráter concorrencial de procedimento licitatório. Citado, o servidor público ofereceu contestação, por meio da sua atuação, na qualidade de advogado(a). Contudo, as preliminares suscitadas pelo réu, na contestação, foram rejeitadas. Em assim sendo, João procurou você, na condição de advogado(a), para tomar conhecimento das próximas etapas procedimentais. Nesse cenário, considerando as disposições da Lei nº 8.429/1992 (Lei de Improbidade Administrativa), assinale a afirmativa correta.','[{"id":"A","text":"A apelação é o recurso cabível para questionar a decisão judicial que rejeitou as questões preliminares suscitadas na contestação."},{"id":"B","text":"A defesa de João poderá interpor agravo de instrumento em detrimento da decisão judicial que rejeitou as questões preliminares suscitadas em sede de contestação."},{"id":"C","text":"Muito embora não seja cabível recurso em face da decisão judicial que rejeitou as questões preliminares suscitadas por João na contestação, nada impede que a defesa formule pedido de reconsideração."},{"id":"D","text":"Por não ter ingressado no mérito da relação processual, a decisão judicial que rejeitou as questões preliminares suscitadas na contestação não é passível de impugnação via recurso ou pedido de reconsideração."}]'::jsonb,'B','oficial',33,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":33}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',34,'Direito Administrativo','As autoridades competentes de determinado órgão federal, diante do grande acúmulo de trabalho, fizeram editar um ato formal delegando parcela de sua competência para outro órgão que a ele não é hierarquicamente subordinado, mediante a especificação das matérias e dos poderes transferidos, os limites da atuação do delegado, a duração e os objetivos da delegação e o recurso cabível. Ao tomar conhecimento de tal fato, Gyslaine ficou muito preocupada quanto à possibilidade de o órgão delegado vir a decidir determinado recurso administrativo que estava tramitando perante o órgão delegante, razão pela qual buscou a sua assessoria jurídica a fim de esclarecer as peculiaridades e os limites da delegação de competência, à luz do disposto na Lei nº 9.784/1999. Assinale a opção que apresenta a informação correta que você, na qualidade de advogado(a), prestou.','[{"id":"A","text":"A competência relativa à decisão de recursos administrativos não pode ser objeto de delegação."},{"id":"B","text":"O ato de delegação é irrevogável, razão pela qual o desfazimento da delegação deve ser objeto de avocação."},{"id":"C","text":"A competência, inexistindo impedimento legal, apenas poderia ser delegada para o órgão hierarquicamente subordinado."},{"id":"D","text":"As decisões adotadas por delegação devem mencionar explicitamente essa qualidade e considerar-se-ão editadas pela autoridade delegante, que detém a competência originária."}]'::jsonb,'A','oficial',34,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":34}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',35,'Direito Ambiental','A sociedade empresária Alfa está em processo de licenciamento ambiental de atividade de tingimento de tecidos e fabricação de roupas, e pretende obter outorga pelo Poder Público do direito do uso de recursos hídricos, consistente em extração de água de aquífero subterrâneo existente no local, como insumo do processo produtivo. Nesse contexto, o empreendedor tomou conhecimento de que será cobrado um valor pelo recurso natural consumido. Inconformado com a cobrança, pois ainda terá grande gasto financeiro com as obras para a extração de água do aquífero, a sociedade empresária procurou a advogada Marcela, especialista em Direito Ambiental, para esclarecer as dúvidas dele acerca da viabilidade de tal exigência. Sobre a cobrança pelo uso da água, à luz dos princípios do Direito Ambiental, assinale a opção que apresenta, corretamente, o esclarecimento dado por Marcela.','[{"id":"A","text":"O empreendedor não deve pagar pelo uso da água, exceto se houver efetivo dano ambiental, com base no princípio de direito ambiental da prevenção."},{"id":"B","text":"A cobrança antecipada por danos ambientais a serem causados por poluidores é pertinente, com base no princípio de direito ambiental do desenvolvimento sustentável."},{"id":"C","text":"O empreendedor deve pagar uma contribuição financeira à coletividade, que sofre as consequências do uso privado da água, com base no princípio de direito ambiental do usuário-pagador."},{"id":"D","text":"A cobrança pelo uso da água não é pertinente, salvo se houver efetivo dano ambiental com a necessária prova pericial que demonstre o nexo causal, com base no princípio de direito ambiental da precaução."}]'::jsonb,'C','oficial',35,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":35}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',36,'Direito Ambiental','O Prefeito do Município Ômega, após os trâmites pertinentes, fez editar um decreto que delimitou uma Área de Proteção Ambiental (APA), unidade de conservação de uso sustentável, em decorrência de sua grande extensão e do grau de ocupação humana, diante de atributos abióticos, bióticos, estéticos ou culturais especialmente importantes para a qualidade de vida e o bem-estar das populações humanas. Dessa maneira busca proteger a diversidade biológica, disciplinar o processo de ocupação e assegurar a sustentabilidade do uso dos recursos naturais. A propriedade privada de Adélia Figueiredo está situada dentro da mencionada unidade de conservação. Preocupada, ela procura você, como advogado, para receber orientação sobre a validade do mencionado decreto e a extensão de seus efeitos, à luz do disposto na Lei nº 9.985/2000. Acerca dessa situação hipotética, assinale a afirmativa correta.','[{"id":"A","text":"As condições para a pesquisa e a visitação do público, observadas as exigências e restrições legais, devem ser estabelecidas por Adélia."},{"id":"B","text":"O Prefeito não poderia ter editado um decreto para a finalidade descrita, pois a Unidade de Conservação Ambiental só pode ser criada por lei."},{"id":"C","text":"A propriedade de Adélia deve ser desapropriada de acordo com o que dispõe a lei, porque está localizada em uma Unidade de Conservação de domínio público."},{"id":"D","text":"A Unidade de Conservação pertence, na realidade, ao grupo das unidades de proteção integral, o que permite o uso dos recursos naturais pelos proprietários privados."}]'::jsonb,'A','oficial',36,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":36}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',37,'Direito Civil','Joaquim Cardoso e Celina de Holanda são pais das gêmeas Clarice e Maria, que têm 17 anos de idade. No ano passado, Clarice, com a devida autorização dos pais, casou-se com Ariano. Maria, no mês de março deste ano, iniciou o curso de Medicina em uma universidade federal. O casal procurou você, como advogado(a) especializado(a) em Direito Civil, para ser orientado sobre a situação jurídica das filhas. A respeito da capacidade civil das filhas de Joaquim e Celina, assinale a afirmativa correta.','[{"id":"A","text":"Como Clarice é casada, ela é civilmente capaz."},{"id":"B","text":"Maria do Carmo, pela matrícula no ensino superior, é civilmente capaz."},{"id":"C","text":"Todas as filhas são relativamente incapazes, pois são maiores de 16 e menores de 18 anos."},{"id":"D","text":"Todas as filhas são absolutamente incapazes, pois são menores de 18 anos, sujeitando-se à autoridade parental."}]'::jsonb,'A','oficial',37,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":37}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',38,'Direito Civil','Joaquim, de 71 anos de idade, é viúvo de Marta há cerca de quatro anos, e não finalizou a partilha de bens deixados por sua falecida esposa, porque há um litígio entre o filho comum do ex-casal e a filha do primeiro casamento de Marta. Na semana passada, Joaquim procurou você, como advogado(a), para ser orientado juridicamente acerca da união que pretende estabelecer com Joana, tendo em vista que a partilha anterior não será realizada antes do novo matrimônio. A respeito do regime de bens que deveria adotar na nova união, assinale a opção que apresenta, corretamente, a sua orientação.','[{"id":"A","text":"Separação convencional de bens, ante a idade de Joaquim."},{"id":"B","text":"Qualquer regime de bens, por força da autonomia que é assegurada a Joaquim."},{"id":"C","text":"Comunhão parcial de bens, de forma a resguardar os bens ainda não partilhados."},{"id":"D","text":"Separação obrigatória de bens, para evitar a confusão patrimonial entre os vínculos conjugais."}]'::jsonb,'D','oficial',38,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":38}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',39,'Direito Civil','Após uma intensa discussão motivada por questões financeiras, Lucas desferiu golpes fatais em seus pais, resultando na morte de ambos, que deixaram uma herança significativa. Mateus, seu irmão mais novo, ainda menor de idade, está sob a tutela de seu tio Ricardo, que se recusa a promover a exclusão de Lucas da sucessão por indignidade. Considerando que Mateus, por ser menor, não tem capacidade legal para agir diretamente, surgem dúvidas sobre quem tem legitimidade para requerer judicialmente a exclusão de Lucas da herança e quais são os procedimentos adequados para isso. Diante da situação hipotética narrada e com base na legislação vigente, assinale a afirmativa correta.','[{"id":"A","text":"Apenas Mateus, ao atingir a maioridade, terá o direito de pedir judicialmente a exclusão de Lucas da sucessão, pois ele é o herdeiro direto prejudicado."},{"id":"B","text":"O Ministério Público tem legitimidade para requerer a exclusão de Lucas por indignidade, protegendo os direitos de Mateus, menor e incapaz de agir por conta própria."},{"id":"C","text":"Apenas Ricardo, na qualidade de tutor de Mateus, pode requerer judicialmente a exclusão de Lucas da sucessão, e a recusa de Ricardo impede que qualquer outra pessoa o faça."},{"id":"D","text":"Lucas só poderá ser excluído da sucessão se Ricardo, na qualidade de tutor, concordar, independentemente da legitimidade de outro herdeiro ou do Ministério Público para a propositura da ação."}]'::jsonb,'B','oficial',39,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":39}'::jsonb);

insert into public.exam_questions (exam_id, question_number, area, prompt, options, correct_option, difficulty, sort_order, source_metadata)
values ('46000000-2026-4000-8000-000000000001',40,'Direito Civil','Lorena resolveu alienar um imóvel avaliado em R$ 2.000.000,00 para Marta. Para tanto, elas elaboraram uma minuta de contrato de compra e venda, especificando as partes, o bem, o preço e a forma de pagamento. Considerando a urgência da vendedora, que iria se mudar para o exterior, essa minuta foi impressa na casa de Marta e assinada pelas partes e pelas testemunhas Natália e Oscar. Sobre a situação hipotética narrada, assinale a afirmativa correta.','[{"id":"A","text":"O contrato de compra e venda é válido, uma vez que, na presença de duas testemunhas, o instrumento particular poderia ser utilizado."},{"id":"B","text":"O contrato de compra e venda é nulo, por desobediência de sua forma, mas poderá ser convertido em promessa de compra e venda."},{"id":"C","text":"O contrato de compra e venda é anulável, por vício de sua forma, decaindo as partes do direito de promover a anulação no prazo de dois anos de sua celebração."},{"id":"D","text":"O contrato de compra e venda é anulável por vício de forma. A lei permite, entretanto, a sua convalidação caso haja o reconhecimento das firmas de todos os envolvidos no Ofício de Notas."}]'::jsonb,'B','oficial',40,'{"source":"46º EOU 2026 - Tipo 1","questionNumber":40}'::jsonb);

commit;
